### ISSUE TITLE
getting error when migrating

### ISSUE THREAD

**Issue by NakulNarayanan007** [nesdis/djongo#1]
Hi,
I've just installed the app using pip , and followed the document. i'm getting a error when i'm trying to migrate 
>     yield from SQLObj.token_2_obj(anIden, parse)

> invalid syntax on djongo/cursor.py", line 337

 Please help me

**Comment by nesdis** [comment]
djongo is MIGRATION FREE. Since mongodb is a schema free DB. you dont need to run manage.py migrate. Simply start using your models DIRECTLY.

In case you change a model, again no need to run a migrateion

**Comment by NakulNarayanan007** [comment]
Hi @nesdis ,
Thank you for your response,
But i'm getting the same error when i take the django-shell

**Comment by nesdis** [comment]
Paste the full stack trace

**Comment by nesdis** [comment]
Hi you require python 3.5 or above to run djongo
