### ISSUE TITLE
Adding automated testing (how to run the tests?)

### ISSUE THREAD

**Issue by WoLpH** [nesdis/djongo#101]
The project has a fairly large amount of tests but I'm not sure how to run them.

To easily test them using multiple environments (python/django versions) tox is a nice solution.

Additionally, it would be nice if those tests would be set up to automatically run through travis (which runs them upon each commit and pull request)

**Comment by nesdis** [comment]
The tests are run currently using the unittest module. The way to run the Django tests is similar to how the Django framework is [unit tested](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/unit-tests/)

I still need to write docs on how to run tests for Djongo related fields.. I have been meaning to integrate and automate this process using travis. Will do it soon.

**Comment by andr0s** [comment]
@nesdis well I don't see an instruction on how to run the tests in README... Still not really sure how to run them... ;)
