### ISSUE TITLE
Problem with adding new field

### ISSUE THREAD

**Issue by giorgi94** [nesdis/djongo#108]
When I create new model, by 
```bash
./manage.py makemigrations
./manage.py migrate
```
everything works fine, but when I add new field to a model, and do migrations, it raises **MigrationError**; Ieven set **ENFORCE_SCHEMA** to false but it doesn't make any change. When I manually add field to mongodb (with defaul value) Exception doesn't raise, but forms are submitted incorrectly.

**Comment by nesdis** [comment]
I have pushed a new fix for this. It should be fixed now
