### ISSUE TITLE
Cannot perform makemigrations

### ISSUE THREAD

**Issue by Anirban1989** [nesdis/djongo#112]
Getting the following error on python3 manage.py makemigrations <aap-name>:

File "/usr/local/lib/python3.4/dist-packages/djongo/sql2mongo/__init__.py", line 24
    self.alias2op: typing.Dict[str, SQLToken] = alias2op
                 ^
SyntaxError: invalid syntax

**Comment by nesdis** [comment]
There is no issue with migrations. Before every push to github, this is one of the basic tests carried out, and it does not fail.

**Comment by Zuum** [comment]
Check you python version to be above the requirements
