### ISSUE TITLE
Django version 1.11

### ISSUE THREAD

**Issue by aayushkothari11** [nesdis/djongo#117]
When I run the makemigrations for the 1st time I get the following error in django==1.11 but everything works fine with django==2.0

Error :
from djongo import models
File "/usr/local/lib/python3.6/dist-packages/djongo/models/__init__.py", line 3, in <module>
from .fields import (
File "/usr/local/lib/python3.6/dist-packages/djongo/models/fields.py", line 28, in <module>
from django.db.models.fields.mixins import FieldCacheMixin
ModuleNotFoundError: No module named 'django.db.models.fields.mixins'

**Comment by nesdis** [comment]
Does not matter as setup.py has the right number. So if you install this from pip, the correct version should automatically get installed for you.

I updated the requirements.txt as well.

**Comment by aayushkothari11** [comment]
I had specifically installed 1.11.8 but anyways thanks

**Comment by arindammanidas** [comment]
Hi @nesdis ,
Do you plan to support Django 1.11? Because it is LTS.
However, I understand that it makes sense to move to 2.0 since you don't support python 2.
