### ISSUE TITLE
can't open admin page

### ISSUE THREAD

**Issue by simba999** [nesdis/djongo#118]
- djongo 1.2.26
- Django 2.0.4

When i open admin page (http://localhost:8000/admin), I got this error.
FAILED SQL: SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = %(0)s ORDER BY "django_admin_log"."action_time" DESC LIMIT 10
Pymongo error: OrderedDict([('ok', 0.0), ('errmsg', "Unrecognized pipeline stage name: '$addFields'"), ('code', 16436)])

**Comment by paolodina** [comment]
MongoDB 3.4 or higher version is a requirement ([Djongo docs](https://github.com/nesdis/djongo#requirements)).

If you are using an older version this is the reason.
