### ISSUE TITLE
ArrayReferenceField issue with issue at " attribute '__getattr__' "

### ISSUE THREAD

**Issue by elisioff** [nesdis/djongo#125]
Hi,

I am trying to create a data base containing "cources" and "exercises" where I would like to have in each course an array of references to existing exercises on the data base. I tried using the ArrayReferenceField but it seems to have some issues with something I am missing.

I tried several variations of the code and noticed that even if I have pretty much every field set to "blank=True" and actually don't add anything to those fields when trying to save them through the admin page, I still get the same error.

Can anyone help please? Greatly appreciate it.

#### ERROR:
'super' object has no attribute '__getattr__'

#### Python code
on "courses.models.py we have

```python
from djongo import models
from django import forms

from exercises.models import Exercise, Tag, TagForm
from custom_users.models import Creator, NormalUser
from submissions.models import Submission

class Course(models.Model):
  _id = models.ObjectIdField()

  name = models.CharField( max_length = 100 )
  description = models.TextField( default="" )
  creator = models.ForeignKey(
    Creator,
    on_delete=models.CASCADE,blank=True
  )
  exercise_list = models.ArrayReferenceField(
    to=Exercise,blank=True
  )
  tags = models.ArrayModelField(
    model_container=Tag,
    model_form_class=TagForm,blank=True
  )
  enrolled = models.ArrayReferenceField(
    to=NormalUser,blank=True
  )
```

and on exercises.models we have
```
from djongo import models
from django import forms
from custom_users.models import Creator


class Tag(models.Model):
  name = models.CharField(max_length=100)
  class Meta:
    abstract = True

class TagForm(forms.ModelForm):
  class Meta:
    model = Tag
    fields = ( 'name', )

class Language(models.Model):
  name = models.CharField(max_length=100)
  class Meta:
    abstract = True

class LanguageForm(forms.ModelForm):
  class Meta:
    model = Language
    fields = ( 'name', )

class Exercise(models.Model):
  _id = models.ObjectIdField()
  name = models.CharField(max_length=100)
  creator = models.ForeignKey(
    Creator,
    on_delete=models.CASCADE,
  )
  description = models.TextField(blank=True)
  tags = models.ArrayModelField(
    model_container=Tag,
    model_form_class=TagForm,
  )
  languages = models.ArrayModelField(
    model_container=Language,
    model_form_class=LanguageForm,blank=True,
  )
  exercise_file = models.FileField(blank=True)
  date_added = models.DateTimeField(auto_now = True)

```

#### Steps to reproduce error
1 open admin page
2 click to add user, Creator and NormalUser
3 add exercise
4 add course -> when trying to save course it  throws and exception

<img width="707" alt="screen shot 2018-05-05 at 14 42 41" src="https://user-images.githubusercontent.com/14952286/39664019-c0578f36-5074-11e8-9680-183eb0323c74.png">

#### Traceback
Environment:

Request Method: POST
Request URL: http://0.0.0.0:8000/admin/courses/course/add/

Django Version: 2.0.4
Python Version: 3.6.5
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'rest_framework',
 'exercises',
 'custom_users',
 'courses']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  574.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  44.         response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  223.             return view(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in add_view
  1553.         return self.changeform_view(request, None, form_url, extra_context)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  62.             return bound_func(*args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  142.                     response = view_func(request, *args, **kwargs)

File "/usr/local/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  58.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in changeform_view
  1450.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in _changeform_view
  1490.                 self.save_model(request, new_object, form, not add)

File "/usr/local/lib/python3.6/site-packages/django/contrib/admin/options.py" in save_model
  1026.         obj.save()

File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py" in save
  679.                 if obj and obj.pk is None:

File "/usr/local/lib/python3.6/site-packages/djongo/models/fields.py" in __getattr__
  80.             return super().__getattr__(name)

Exception Type: AttributeError at /admin/courses/course/add/
Exception Value: 'super' object has no attribute '__getattr__'

**Comment by nesdis** [comment]
HI

The ArrayReferenceField is still not fully functional, and is still under development

**Comment by nesdis** [comment]
Hi @elisioff 

Please let me know the version of Djongo you are using

**Comment by elisioff** [comment]
hi @nesdis,

how do I check Djongo's version?

**Comment by elisioff** [comment]
hi @nesdis ,

found it . the version is djongo-1.2.29

thanks

**Comment by snregales** [comment]
I have a similar problem
djongo-1.2.28
ArrayModelField I am easily able to add an object to Array Model, with methods similar to how you append or extend with a list object in python. But same cannot be said for ArrayReferenceField. Hopefully, you are able to help all I need is a way to append or extend a reference to the end of the Array

**Comment by dblado** [comment]
@elisioff from command line run:
pip freeze|grep djongo
-  or  -
cat /usr/local/lib/python3.6/site-packages/djongo/__init__.py

**Comment by snregales** [comment]
I figured some of it out
____________________________________________

from djongo import models


class Relation(models.Model):
    slug = models.SlugField(primary_key=True)
    line = models.CharField(max_length=255, unique=True)
    objects = models.DjongoManager()

    def __str__(self):
        return self.line


class Related(models.Model):
    slug = models.SlugField(primary_key=True)
    doc = models.CharField(max_length=255, unique=True)
    words = models.ArrayReferenceField(
        to=Relation,
        on_delete=models.CASCADE,
    )
    objects = models.DjongoManager()

    def __str__(self):
        return self.doc

_________________________________________________

>>> rel, created = related.words.update_or_create(**{'slug': 'kandel-was-here', 'line': 'Kandel-was-here'})
>>> rel
<Relation: Kandel-was-here>
>>> related.words.add(*[rel])
>>> related.words.all()
<QuerySet [<Relation: Kandel is home>, <Relation: Kandel-was-here>]>

**Comment by dblado** [comment]
Has anyone been able to get an ArrayReferenceField to work?

I have a tree structure where documents optionally have children and a parent:

```py3
class Category(models.Model):
    _id = models.ObjectIdField()
    children = models.ArrayReferenceField('self', related_name='category_children', on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=60)
    parent = models.ForeignKey('self', blank=True, on_delete=models.DO_NOTHING)

    objects = models.DjongoManager()

```
**When I try:**
```py3
cat = Category.objects.get(_id='53542721c61e3644fe385188')
newcat = Category.objects.create(name='test3', children=[cat2])
```
**I get the following stacktrace:**
```py3
---------------------------------------------------------------------------
DoesNotExist                              Traceback (most recent call last)
<ipython-input-2-435bf53bb358> in <module>()
     17 print(cat2)
     18 
---> 19 newcat=Category.objects.create(name='test3', children=[cat2])
     20 # print(newcat.children)
     21 # newcat.children.append(cat2)

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     80         def create_method(name, method):
     81             def manager_method(self, *args, **kwargs):
---> 82                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     83             manager_method.__name__ = method.__name__
     84             manager_method.__doc__ = method.__doc__

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/query.py in create(self, **kwargs)
    415         obj = self.model(**kwargs)
    416         self._for_write = True
--> 417         obj.save(force_insert=True, using=self.db)
    418         return obj
    419 

~/vendop/www/categories/models.py in save(self, *args, **kwargs)
     40     def save(self, *args, **kwargs):
     41         cache.delete('category_tree')
---> 42         return super(Category, self).save(*args, **kwargs)
     43 
     44     @property

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/base.py in save(self, force_insert, force_update, using, update_fields)
    727 
    728         self.save_base(using=using, force_insert=force_insert,
--> 729                        force_update=force_update, update_fields=update_fields)
    730     save.alters_data = True
    731 

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/base.py in save_base(self, raw, force_insert, force_update, using, update_fields)
    757             if not raw:
    758                 self._save_parents(cls, using, update_fields)
--> 759             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    760         # Store the database on which the object was saved
    761         self._state.db = using

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/base.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)
    840 
    841             update_pk = meta.auto_field and not pk_set
--> 842             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    843             if update_pk:
    844                 setattr(self, meta.pk.attname, result)

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/base.py in _do_insert(self, manager, using, fields, update_pk, raw)
    878         """
    879         return manager._insert([self], fields=fields, return_id=update_pk,
--> 880                                using=using, raw=raw)
    881 
    882     def delete(self, using=None, keep_parents=False):

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     80         def create_method(name, method):
     81             def manager_method(self, *args, **kwargs):
---> 82                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     83             manager_method.__name__ = method.__name__
     84             manager_method.__doc__ = method.__doc__

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/query.py in _insert(self, objs, fields, return_id, raw, using)
   1123         query = sql.InsertQuery(self.model)
   1124         query.insert_values(fields, objs, raw=raw)
-> 1125         return query.get_compiler(using=using).execute_sql(return_id)
   1126     _insert.alters_data = True
   1127     _insert.queryset_only = False

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py in execute_sql(self, return_id)
   1282         self.return_id = return_id
   1283         with self.connection.cursor() as cursor:
-> 1284             for sql, params in self.as_sql():
   1285                 cursor.execute(sql, params)
   1286             if not (return_id and cursor):

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py in as_sql(self)
   1235             value_rows = [
   1236                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1237                 for obj in self.query.objs
   1238             ]
   1239         else:

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1235             value_rows = [
   1236                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1237                 for obj in self.query.objs
   1238             ]
   1239         else:

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1234         if has_fields:
   1235             value_rows = [
-> 1236                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
   1237                 for obj in self.query.objs
   1238             ]

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/sql/compiler.py in pre_save_val(self, field, obj)
   1184         if self.query.raw:
   1185             return getattr(obj, field.attname)
-> 1186         return field.pre_save(obj, add=True)
   1187 
   1188     def assemble_as_sql(self, fields, value_rows):

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/fields/__init__.py in pre_save(self, model_instance, add)
    745     def pre_save(self, model_instance, add):
    746         """Return field's value just before saving."""
--> 747         return getattr(model_instance, self.attname)
    748 
    749     def get_prep_value(self, value):

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/query_utils.py in __get__(self, instance, cls)
    134             val = self._check_parent_chain(instance, self.field_name)
    135             if val is None:
--> 136                 instance.refresh_from_db(fields=[self.field_name])
    137                 val = getattr(instance, self.field_name)
    138             data[self.field_name] = val

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/base.py in refresh_from_db(self, using, fields)
    614             db_instance_qs = db_instance_qs.only(*fields)
    615 
--> 616         db_instance = db_instance_qs.get()
    617         non_loaded_fields = db_instance.get_deferred_fields()
    618         for field in self._meta.concrete_fields:

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/django/db/models/query.py in get(self, *args, **kwargs)
    401             raise self.model.DoesNotExist(
    402                 "%s matching query does not exist." %
--> 403                 self.model._meta.object_name
    404             )
    405         raise self.model.MultipleObjectsReturned(

DoesNotExist: Category matching query does not exist.
```
**When I try:**
```py3
cat = Category.objects.get(_id='53542721c61e3644fe385188')
newcat = Category.objects.create(name='test3')
print(newcat.children)
newcat.children.append(cat2)
print(newcat.children)
newcat.save()
```
**I get the following stacktrace:**
```py3
categories.Category.None
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-1c96403b2522> in <module>()
     19 newcat=Category.objects.create(name='test3')#, children=[cat2])
     20 print(newcat.children)
---> 21 newcat.children.append(cat2)
     22 print(newcat.children)
     23 # newcat.children_id=[cat2._id]

~/.virtualenvs/vendop_py36/lib/python3.6/site-packages/djongo/models/fields.py in __getattr__(self, name)
     76             return getattr(cli, name)
     77         else:
---> 78             return super().__getattr__(name)
     79 
     80 

AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by dblado** [comment]
Updated to the latest djongo (master commit 30cc17e75501dafa28ba5684072b397e41e8a42e) and I am able to use:
```py3
cat = Category.objects.get(_id='53542721c61e3644fe385188')
newcat = Category.objects.create(name='test3')
newcat.children.add(cat2)
newcat.save()
```

**Comment by nesdis** [comment]
Issue has been fixed

**Comment by pritamgb** [comment]
Facing this issue but with mongo_aggregate().

> Error: AttributeError: 'super' object has no attribute '__getattr__'

Model.objects.mongo_aggregate(pipeline).using("mongodb")

My model has 
objects = models.DjongoManager()

**Comment by juandavidvallejo** [comment]
Has anyone fixed the ArrayReferenceField in django admin? Just save one value and not an array as it should work, please help
