### ISSUE TITLE
Can't get model._id or model.pk after save

### ISSUE THREAD

**Issue by abawchen** [nesdis/djongo#138]
Hi, thanks for the great library, It saves my day 👍 

But I can't get model._id after save -- Do I miss something?

My model
```python
class License(models.Model):
     _id = models.ObjectIdField()

    name = models.CharField(
        max_length=255,
    )

    url = models.CharField(
        max_length=255,
    )
```

Can't get `_id` after save:
```python
license = License(name="test")
license.save()
license._id # None here
license.pk # None here
```

**Comment by nesdis** [comment]
Sorry, recent changes broke this, but this has been fixed. will push the change asap

**Comment by nesdis** [comment]
this has been fixed

**Comment by abawchen** [comment]
@nesdis : Thanks for the fix!
