### ISSUE TITLE
The AutoField `id` would be treated as `float`

### ISSUE THREAD

**Issue by abawchen** [nesdis/djongo#142]
The AutoField `id` would be treated as `float` if I manually modify the `auto.seq` value in `__schema__` (i.e. I get `1.0` instead of `1`)

Currently I convert it to int `djongo.sql2mongo/query.py` as follows:

```python
ins[name] = int(auto['auto']['seq'] - num + i + 1)  #427
self._result_ref.last_row_id = int(auto['auto']['seq']) #439
```
Can I create a pull request for it? Does it make sense?

** The reason I modify the `auto.seq` is that we migrate data from the legacy MySQL and we want to keep the same numeric `id` we used.

**Comment by abawchen** [comment]
I found converting id to int manually in `__schema__` table fixes this one.

**Comment by 11abuyaman** [comment]
Hello, I'm facing this issue and can't quite solve it! how did you solve it? please.
