### ISSUE TITLE
how about adding models.EmbeddedModel

### ISSUE THREAD

**Issue by dblado** [nesdis/djongo#150]
Thoughts on adding something like this to djongo.models:

```python
class EmbeddedModel(django's Model class):
    class Meta:
        abstract = True
```

Then in your Djongo model you could do:
```python
class MyEmbeddedModel(models.EmbeddedModel):
    fieldA = models.CharField()
```

would make it easier to understand a models purpose without having to look for the abstract = True.

**Comment by nesdis** [comment]
Although the parent '`EmbeddedModel` is abstract the child `MyEmbeddedModel` will not be. And Django will create an entry for this in DB which we do not want.

**Comment by dblado** [comment]
Ahh, didn't know that Django would set abstract=False on models inheriting from an abstract base class.
