### ISSUE TITLE
[BUG] djongo.sql2mongo.SQLDecodeError

### ISSUE THREAD

**Issue by mazhar266** [nesdis/djongo#153]
#### Python script
I just tried to access django admin panel . I'm using Django 2.0.6 and python 3.7.

#### Traceback
```
djongo.sql2mongo.SQLDecodeError: FAILED SQL: SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = %(0)s ORDER BY "django_admin_log"."action_time" DESC LIMIT 10
Pymongo error: OrderedDict([('ok', 0.0), ('errmsg', "Unrecognized pipeline stage name: '$addFields'"), ('code', 16436)])
Version: 1.2.29
[03/Jul/2018 06:58:46] "GET /admin/ HTTP/1.1" 500 387008

```

**Comment by aleks-fr** [comment]
Hi 
Hi @mazhar266 any update on this ?
I also have same this issue

Im use python 3.6.2 and Django 2.05

**Comment by mazhar266** [comment]
@aleks-fr I have fixed it by installing the latest version of MongoDB and removing the package `django-reversion`.

**Comment by vickyboston20** [comment]
djongo.sql2mongo.SQLDecodeError: FAILED SQL: INSERT INTO "django_migrations" ("app", "name", "applied") VALUES (%(0)s, %(1)s, %(2)s)
Version: 1.2.31

Im also getting same error while migrating pls guide me to solve this error.


![error](https://user-images.githubusercontent.com/20809841/54474109-ad89be80-4806-11e9-9a07-6ae3870530d9.PNG)

**Comment by ybloch** [comment]
for me it's was the sqlparse version, the version that worked for me is - sqlparse==0.2.4 (pip install sqlparse==0.2.4)

**Comment by robertour** [comment]
`pip install sqlparse==0.2.4` solved my issue in `Python 3.7.3` and `Django 2.1.7`

**Comment by mazhar266** [comment]
Recently I faced this again after upgrading the package to 1.2.32. I fixed this by downgrading the package to version 1.2.31

**Comment by mafiagamer** [comment]
@mazhar266 how to downgrade the version ? what version should be downgraded ?

**Comment by mazhar266** [comment]
`pip install djongo==1.2.31` @mafiagamer

**Comment by tongxin97** [comment]
Downgrading `sqlparse` and `djongo` does not work for me (`Python` 3.7.1, `Django` 2.2.6)

**Comment by fannyhub** [comment]
it seems that downgrading does not help if you are using docker

**Comment by ybloch** [comment]
> it seems that downgrading does not help if you are using docker

To me, this solved the problem with Docker too

**Comment by fannyhub** [comment]
> > it seems that downgrading does not help if you are using docker
> 
> To me, this solved the problem with Docker too

well, good for you :)
I've downgraded sqlparse to 0.2.4 and djongo to 1.2.31, as recommended, but still get jongo.sql2mongo.SQLDecodeError: FAILED SQL: INSERT INTO "auth_user" when trying just to create superuser.

**Comment by ybloch** [comment]
> > > it seems that downgrading does not help if you are using docker
> > 
> > 
> > To me, this solved the problem with Docker too
> 
> well, good for you :)
> I've downgraded sqlparse to 0.2.4 and djongo to 1.2.31, as recommended, but still get jongo.sql2mongo.SQLDecodeError: FAILED SQL: INSERT INTO "auth_user" when trying just to create superuser.

So it's nothing to do with Docker, I think the solution fits only for django 2 or higher, 
I'm using:
django==2.1.4
sqlparse==0.2.4

**Comment by fannyhub** [comment]
Ok afer all it works :))) the problem was on DATABASES setting, there was a wrong host

**Comment by eldano1995** [comment]
Upgrading the MongoDB version work for me: I was using version 3.2 and the djongo requires 3.4.
