### ISSUE TITLE
trying to create embedded doc and array of embedded docs

### ISSUE THREAD

**Issue by dchan14** [nesdis/djongo#19]
#### One line description of the issue
just trying to the embedded doc feature in the admin forms. when i use EmbeddedModelField i get this required field error and it won't save.  when i use ArrayModelField i get html text below instead of the table rendered.  following example https://nesdis.github.io/djongo/  
Thanks much!! this is an awesome start for mongo support.

#### Python script

```python
class logSchema(models.Model):
    comment = models.TextField()
    userName = models.CharField(max_length=80)

    class Meta:
        abstract = True


class logForm(forms.ModelForm):
    class Meta:
        model = logSchema
        fields = [
            'comment', 'userName'
        ]

class EmbeddedDocTest(models.Model):
    log = models.ArrayModelField(model_container=logSchema,
                                 model_form=logForm)

```

#### Traceback
Log: <table> <input type="hidden" name="log-TOTAL_FORMS" value="1" id="id_log-TOTAL_FORMS" /><input type="hidden" name="log-INITIAL_FORMS" value="0" id="id_log-INITIAL_FORMS" /><input type="hidden" name="log-MIN_NUM_FORMS" value="0" id="id_log-MIN_NUM_FORMS" /><input type="hidden" name="log-MAX_NUM_FORMS" value="1000" id="id_log-MAX_NUM_FORMS" /> <tr><th><label for="id_log-0-comment">Comment:</label></th><td><textarea name="log-0-comment" cols="40" rows="10" id="id_log-0-comment"> </textarea></td></tr> <tr><th><label for="id_log-0-userName">UserName:</label></th><td><input type="text" name="log-0-userName" maxlength="80" id="id_log-0-userName" /></td></tr> <tr><th><label for="id_log-0-DELETE">Delete:</label></th><td><input type="checkbox" name="log-0-DELETE" id="id_log-0-DELETE" /></td></tr> </table>

**Comment by nesdis** [comment]
I am not able to see the trace back. Can you please put it up again

**Comment by dchan14** [comment]
Sorry about not being clear but there are no errors it just doesn't let me
save as embedded software

And as an arrayfield that table doesn't display it displays as HTML string

**Comment by nesdis** [comment]
I have added some new tests to test_models.py. 

```python
class TestWithDjango(TestCase):

    def test_models(self):
        embedded = Embedded(text='embedded text')
        test = Dummy(test='test data', embedded=embedded)
        test.save()
        # tdel = Dummy.objects.get(test='test data')
        embedded_array = Dummies(h1='heading', content=[embedded, embedded])
        embedded_array.save()

```

When I run the test, in my mongodb, the following documents get created:

```
{ 
    "_id" : ObjectId("5a082b86a1b5e32de1fccf7b"), 
    "h1" : "heading", 
    "content" : [
        {
            "text" : "embedded text"
        }, 
        {
            "text" : "embedded text"
        }
    ]
}

```
Do a git clone to get this latest release. 

Try running the test file to see if it works on your project
