### ISSUE TITLE
Dificulty to start with Djongo

### ISSUE THREAD

**Issue by alvaroseparovich** [nesdis/djongo#20]
#### Syntax Error in sql2mongo.py
I tryed to run "manage.py migrate" to use Djongo, but it don't finish well.  He indicate invalid syntax on "lib/python3.5/site-packages/djongo/sql2mongo.py", line 47 on ":"

#### "sql2mongo.py", line 46, 47, 48
```python

class CollField(typing.NamedTuple):
    coll: str
    field: str

```

what i'm doing wrong?

**Comment by nesdis** [comment]
Please update to python 3.6 it should work
