### ISSUE TITLE
embedded model work in test but not in admin interface

### ISSUE THREAD

**Issue by dchan14** [nesdis/djongo#21]
#### One line description of the issue
embedded model work in test but not in admin interface

**Does the class Dummy below need model_form=DummyForm ?  if I don't put that in I get an error**
#### Traceback
Request Method: | GET
-- | --
http://localhost:8000/admin/dummy/dummy/add/
1.11.7
ValidationError
['Implementing model form class needed to create field']
/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/djongo/models.py in formfield, line 266
/home/chanda/Documents/trackerpython3/bin/python
3.6.3
['/home/chanda/Documents/djongo/tests/dummy_app',  '/home/chanda/Documents/trackerpython3/lib/python36.zip',  '/home/chanda/Documents/trackerpython3/lib/python3.6',  '/home/chanda/Documents/trackerpython3/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages']
Fri, 17 Nov 2017 08:05:39 +0000

**if I add the mode_form=DummyForm into Dummy class I get the error below but at least i get to see the admin fields for Dummy.**
#### Traceback
Request Method: | POST
-- | --
http://localhost:8000/admin/dummy/dummy/add/
1.11.7
AttributeError
'DummyForm' object has no attribute 'model'
/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/djongo/models.py in compress, line 310
/home/chanda/Documents/trackerpython3/bin/python
3.6.3
['/home/chanda/Documents/djongo/tests/dummy_app',  '/home/chanda/Documents/trackerpython3/lib/python36.zip',  '/home/chanda/Documents/trackerpython3/lib/python3.6',  '/home/chanda/Documents/trackerpython3/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages']
Fri, 17 Nov 2017 07:42:56 +0000

#### Python script
```python
class Embedded(models.Model):
    text = models.CharField(max_length=100)

    class Meta:
        abstract = True


class Dummy(models.Model):

    test = models.CharField(max_length=10)
    embedded = models.EmbeddedModelField(model_container=Embedded)

class Dummy2(models.Model):

    test = models.CharField(max_length=10)
    embedded = models.EmbeddedModelField(model_container=Embedded)

class DummyForm(models.forms.ModelForm):
    class Meta:
        model = Embedded
        fields = (
            'text',
        )


class Dummies(models.Model):
    h1 = models.CharField(max_length=100)
    content = models.ArrayModelField(
        model_container=Embedded,
        model_form=DummyForm
    )


```

**So the tests do work and does insert embedded docs into the collection.  I just want to know if the admin interface work with embedded docs.**

**Thanks again for the quick responses and updates!**

**Comment by dchan14** [comment]
I added model_form and blank=True to the Dummy model and i get this error now:
Environment:


Request Method: POST
Request URL: http://localhost:8000/admin/dummy/dummy/add/

Django Version: 1.11.7
Python Version: 3.6.3
Installed Applications:
['dummy.apps.DummyConfig',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/contrib/admin/options.py" in wrapper
  551.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/contrib/admin/sites.py" in inner
  224.             return view(request, *args, **kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/contrib/admin/options.py" in add_view
  1508.         return self.changeform_view(request, None, form_url, extra_context)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  67.             return bound_func(*args, **kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/utils/decorators.py" in bound_func
  63.                 return func.__get__(self, type(self))(*args2, **kwargs2)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/contrib/admin/options.py" in changeform_view
  1408.             return self._changeform_view(request, object_id, form_url, extra_context)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/contrib/admin/options.py" in _changeform_view
  1440.             if form.is_valid():

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/forms/forms.py" in is_valid
  183.         return self.is_bound and not self.errors

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/forms/forms.py" in errors
  175.             self.full_clean()

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/forms/forms.py" in full_clean
  384.         self._clean_fields()

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/forms/forms.py" in _clean_fields
  402.                     value = field.clean(value)

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/django/forms/fields.py" in clean
  1031.                     return self.compress([])

File "/home/chanda/Documents/trackerpython3/lib/python3.6/site-packages/djongo/models.py" in compress
  310.         return self.mdl_form.model(**mdl_fi)

Exception Type: AttributeError at /admin/dummy/dummy/add/
Exception Value: 'DummyForm' object has no attribute 'model'

**Comment by nesdis** [comment]
HI

In my test file if I change the model like so:

```python
class Dummies(models.Model):
    h1 = models.CharField(max_length=100)
    content = models.ArrayModelField(
        model_container=Embedded,
    )
```
I am not including  `model_form=DummyForm` as None is a valid argument. I get no error.

Regarding using embedded model in admin interface, there is an issue. For the time being though you may try manipulating the models directly in your script itself (without the gui).

**Comment by dchan14** [comment]
Yes I am able to use it outside of admin interface.
Thanks for looking into the issue.
Great work by the way!

On Nov 19, 2017 7:50 AM, "nesdis" <notifications@github.com> wrote:

HI

In my test file if I change the model like so:

class Dummies(models.Model):
    h1 = models.CharField(max_length=100)
    content = models.ArrayModelField(
        model_container=Embedded,
    )

I am not including model_form=DummyForm as None is a valid argument. I get
no error.

Regarding using embedded model in admin interface, there is an issue. For
the time being though you may try manipulating the models directly in your
script itself (without the gui).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nesdis/djongo/issues/21#issuecomment-345514128>, or mute
the thread

**Comment by nesdis** [comment]
The issue with admin interface not being able to update embedded documents has been fixed. You can now use the admin interface to update embedded documents. 

I have pushed the changes to git. You can clone a copy to test it with your project.
