### ISSUE TITLE
Models in ArrayModelField do not show the right widget

### ISSUE THREAD

**Issue by thestick613** [nesdis/djongo#213]
If a add a `date_added = models.DateTimeField()` field in a widget, django-admin displays it like this:

<img width="435" alt="screen shot 2018-11-10 at 13 56 23" src="https://user-images.githubusercontent.com/1608525/48301122-1972b800-e4f1-11e8-8453-ff8c49a8e04e.png">

If i embed that field into an embedded model, it stops displaying the nice widget:

```
class Container(models.Model):
    _id = models.CharField(max_length=256)
    date_added = models.DateTimeField()

class Entry(models.Model):
    lists = models.ArrayModelField(model_container=Container)

```
<img width="651" alt="screen shot 2018-11-10 at 13 57 00" src="https://user-images.githubusercontent.com/1608525/48301128-4cb54700-e4f1-11e8-8c55-d81175e47422.png">

**Comment by mortezadalil** [comment]
I have same issue

**Comment by mortezadalil** [comment]
use "save and continue editing" instead "save" button.
![image](https://user-images.githubusercontent.com/15077932/49292398-62030d00-f4c2-11e8-9cec-eaad7e3b67e6.png)

**Comment by arindammanidas** [comment]
Can you show your code in admin.py file?

**Comment by thestick613** [comment]
```
@admin.register(Entry)
class EntryAdmin(admin.ModelAdmin):
    list_display = ('lists',)
    form = EntryForm

[...]

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ('lists', )

```

Why do you ask, does this work for you?

**Comment by arindammanidas** [comment]
I wanted to see if there's something there which is causing the widget not to be rendered properly. I just tried it out as well, and you're right - datetime field widgets don't show up incase of an embedded field or array model field.

**Comment by kochomati** [comment]
@arindammanidas @thestick613 
Any solution to this? Also, how do we make it so that the admin interface allows you to add more dates (or any other type of field within the Container model)?

**Comment by nesdis** [comment]
The reason why it works for fields not included inside embedded field is that django-admin overrides every field, with its own custom fields. 

ex:
```

    models.DateTimeField: {
        'form_class': forms.SplitDateTimeField,
        'widget': widgets.AdminSplitDateTime
    },
    models.DateField: {'widget': widgets.AdminDateWidget},
    models.TimeField: {'widget': widgets.AdminTimeWidget},
    models.TextField: {'widget': widgets.AdminTextareaWidget},
    models.URLField: {'widget': widgets.AdminURLFieldWidget},

```

As of today there is no way to introduce 'custom admin field' for an EmbeddedModelField. if you don't however use django admin, you can still get this widget in.

**Comment by thestick613** [comment]
An easy trick to solve this is to add a non-embedded field which uses the same widget. The embedded field widget now appears.

**Comment by nesdis** [comment]
@thestick613 What do you mean by 

> non-embedded field which uses the same widget

Can you paste the source code?

**Comment by thestick613** [comment]
First time i used this trick, i used it for a django-autocomplete field.

If you put a django autocomplete widget in the container model form, it won't display. If you also put a dummy django autocomplete widget in the base model which contains one of the container forms, the embedded one will start working. You only need to do it in order to load the needed javascript.

This trick doesn't work so easily for a datetime widget, but you can make it work with some extra hacks:

This doesn't display it:
```
class Container(models.Model):
    _id = models.CharField(max_length=256)
    date_added = models.DateTimeField()

class Entry(models.Model):
    lists = models.ArrayModelField(model_container=Container)
```

But this should:
```
class Container(models.Model):
    _id = models.CharField(max_length=256)
    date_added = models.DateTimeField()

from dateutil.parser import parse as parse_dt
from django.contrib.admin.widgets import AdminSplitDateTime


class DTWidget(AdminSplitDateTime):
    def value_from_datadict(self, data, files, name):
        temp = [widget.value_from_datadict(data, files, name + '_%s' % i) for i, widget in enumerate(self.widgets)]
        if temp[0] and temp[1]:
            return parse_dt(' '.join(temp))
        return None

class ContainerForm(models.Model):
    class Meta:
        model = Container
        widgets = {
            'date_added': DTWidget()
        }

class Entry(models.Model):
    lists = models.ArrayModelField(model_container=Container, model_form_class=ContainerForm)
    some_date = models.DateTimeField() # you also need this one in order for django to load the needed js for the embedded one.
```
