### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by nesdis** [nesdis/djongo#23]
1. Fix the Bulk insert feature in Django, Currently it has been disabled as reported in this bug report:

   https://github.com/silentreaper/djongo/issues/1

2. Write a test case that makes sure bulk insert actually gets triggered.

**Comment by Vichoko** [comment]
Bulk insert is the same that [Bulk Create](https://docs.djangoproject.com/en/2.2/ref/models/querysets/#django.db.models.query.QuerySet.bulk_create) method?

If it is, i don't think it's properly disabled because it doesn't throw any exception ir just doesn't work.
