### ISSUE TITLE
AssertionError at /admin/rdm/item/

### ISSUE THREAD

**Issue by thecortex** [nesdis/djongo#24]
#### One line description of the issue
AssertionError at /admin/rdm/item/
No exception message supplied

#### Python script
`STORE_CHOICES = (
        ('amazon', 'Amazon'),
        ('walmart', 'Walmart'),
        ('bestbuy', 'BestBuy')
    )

class Image(models.Model):
    url = models.CharField(max_length=2048, blank= True)
    custom = models.ImageField(blank= True)
    class Meta:
        abstract = True

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = (
            "url",
            "custom"
        )

class NestedCategory(models.Model):
    title = models.CharField(max_length=2048, blank= True)
    class Meta:
        abstract = True

class NestedCategoryForm(forms.ModelForm):

    class Meta:
        model = NestedCategory
        fields = (
            "title",
        )

class Rating(models.Model):
    source = models.CharField(max_length= 100, choices= STORE_CHOICES, default = 'amazon', blank= True)
    value = models.FloatField(blank= True)
    number = models.IntegerField(blank= True)
    class Meta:
        abstract = True

class RatingForm(forms.ModelForm):

    class Meta:
        model = Rating
        fields = (
            "source",
            "value",
            "number"
        )

class InternalPriceChange(models.Model):
    source = models.CharField(max_length= 100, choices= STORE_CHOICES, default = 'amazon', blank= True)
    value = models.FloatField(blank= True)
    timestamp = models.FloatField(default= time.time, blank= True)
    class Meta:
        abstract = True

class InternalPriceChangeForm(forms.ModelForm):

    class Meta:
        model = InternalPriceChange
        fields = (
            "source",
            "value",
            "timestamp"
        )

class Item(models.Model):
    objects = models.DjongoManager()
    RIBBON_RANK_CHOICES = (
        ('', ''),
        ('bestDealEver', 'Best Deal Ever'),
        ('rareDeal', 'Rare Deal'),
        ('realDeal', 'RealDeal')
    )
    upc = models.BigIntegerField(blank= False)
    title = models.CharField(blank= False, max_length= 2048)
    brand = models.CharField(max_length= 500, blank= True)
    binding = models.CharField(max_length= 1024, blank= True)
    dealHackerRank = models.IntegerField(blank=True, default= 0)
    amazonSalesRank = models.IntegerField(blank= True)
    walmartSalesRank = models.IntegerField(blank= True)
    bestbuySalesRank = models.IntegerField(blank= True)
    attrImpressions = models.IntegerField(blank= True)
    attrLikes = models.IntegerField(blank= True)
    attrSaves = models.IntegerField(blank= True)
    attrClicks = models.IntegerField(blank= True)
    attrCTR = models.FloatField(blank= True)
    attrRibbonRank = models.CharField(max_length= 100, choices= RIBBON_RANK_CHOICES, default= '', blank= True)
    isBestSeller = models.BooleanField()
    isMostGifted = models.BooleanField()
    isCustomerTopRated = models.BooleanField()
    isMostViewed = models.BooleanField()
    ratingsTotalNumber = models.IntegerField(blank= True)
    ratingsAverage = models.FloatField(blank= True)
    primaryImage = models.CharField(max_length= 2048)
    images = models.ArrayModelField(
        model_container = Image,
        model_form = ImageForm,
        blank= True
    )
    categories = models.ArrayModelField(
        model_container = NestedCategory,
        model_form = NestedCategoryForm,
        blank = True
    )
    ratings = models.ArrayModelField(
        model_container = Rating,
        model_form = RatingForm,
        blank= True
    )
    internalPriceChanges = models.ArrayModelField(
        model_container = InternalPriceChange,
        model_form = InternalPriceChangeForm,
        blank= True
    )`
<The complete python script used to produce the issue.>

```
python

```

#### Traceback

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/rdm/item/
1.11.7
AssertionError
/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/djongo/models.py in to_python, line 91
/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/bin/python
3.6.3
['/home/qamar-ud-din/HackerDeals',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python36.zip',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages',  '/home/qamar-ud-din/HackerDeals']
Tue, 5 Dec 2017 14:40:30 +0000

Request Method: | GET
-- | --
http://127.0.0.1:8000/admin/rdm/item/
1.11.7
AssertionError
/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages/djongo/models.py in to_python, line 91
/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/bin/python
3.6.3
['/home/qamar-ud-din/HackerDeals',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python36.zip',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/qamar-ud-din/.virtualenvs/HackerDeals-KUN3UhSm/lib/python3.6/site-packages',  '/home/qamar-ud-din/HackerDeals']
Tue, 5 Dec 2017 14:40:30 +0000

`Database Object
{
	"_id" : ObjectId("5a26ace7053541470b4c088e"),
	"title" : "Sonic & All-Stars Racing Transformed Bonus Edition - Nintendo Wii U",
	"upc" : NumberLong("10086671018"),
	"primaryImage" : "https://img.bbystatic.com/BestBuy_US/images/products/6907/6907979_sa.jpg",
	"amazonSalesRank" : null,
	"brand" : "Sumo Digital",
	"categories" : [
		{
			"title" : "Best Buy"
		},
		{
			"title" : "Video Games"
		},
		{
			"title" : "Wii U"
		},
		{
			"title" : "Wii U Games"
		}
	],
	"ratings" : [
		{
			"source" : "",
			"value" : 4.4,
			"number" : 113
		}
	],
	"ratingsAverage" : 4.4,
	"ratingsTotalNumber" : 113,
	"images" : [
		{
			"url" : "http://images.com/123.jpg",
			"custom" : ""
		}
	],
	"bestbuySalesRank" : 126816,
	"walmartSalesRank" : null,
	"binding" : "",
	"attrImpressions" : 0,
	"attrLikes" : 0,
	"attrSaves" : 0,
	"attrClicks" : 0,
	"attrCTR" : 0,
	"attrRibbonRank" : "",
	"isBestSeller" : false,
	"isMostGifted" : false,
	"isCustomerTopRated" : false,
	"isMostViewed" : false,
	"dealHackerRank" : 0,
	"id" : 1,
	"internalPriceChanges" : [
		{
			"source" : "amazon",
			"value" : null,
			"timestamp" : 1512484254.969009
		}
	]
}

`

**Comment by nesdis** [comment]
it is not clear what is your error. 
I tried adding your model to django admin. I am able to save and retrieve the model. take a look at the screenshot

When exactly are you getting this exception? Have to upgraded to latest version of djongo

![image](https://user-images.githubusercontent.com/17020932/33618470-a83071c6-da08-11e7-9f44-8928ead18a06.png)

**Comment by nesdis** [comment]
Django admin works fine for me with the models you have provided. So i am closing this
