### ISSUE TITLE
gunicorn doesn't support python3.6

### ISSUE THREAD

**Issue by thecortex** [nesdis/djongo#25]
#### One line description of the issue
gunicorn doesn't read python3.6 and therefore not read djongo
how to make gunicorn read python path from python 3.6

#### Python script

<The complete python script used to produce the issue.>

```python
<copy and paste code here>

```

#### Traceback
<The complete stack trace of the error.>

**Comment by nesdis** [comment]
Djongo requires python 3.6 to run

**Comment by nesdis** [comment]
If your package works on lower version of python3 it should on a higher version as well.
