### ISSUE TITLE
After manually creating records cannot insert any records with django

### ISSUE THREAD

**Issue by d6tdev** [nesdis/djongo#250]
After If I manually create records, I cannot create any records with django because it hasnt realized the auto index has gone up and wants to create a duplicate index which fails. `sqlsequencereset` doesn't help. SQLite doesn't have this problem it just uses the max index and increments.

#### questions?

where does it keep track of the last index to increment? how can it be reset?

#### replicate

https://github.com/jruizvar/django-tutorial => migrate, createsuperuser

```python
from pymongo import MongoClient
client = MongoClient()
db = client['polls1']

import datetime
db['polls_question'].insert_one({'id':1,'question_text':'test1','pub_date':datetime.datetime.now()})

for i in db['polls_question'].find():
    print(i) 

```
{'_id': ObjectId('5ca02858841ed81baad7ddbd'), 'id': 1, 'question_text': 'test1', 'pub_date': datetime.datetime(2019, 3, 30, 22, 39, 20, 132000)}

#### trace

http://127.0.0.1:8000/admin/polls/question/add/ => try to create a record

```
SQLDecodeError at /admin/polls/question/add/

FAILED SQL: INSERT INTO "polls_question" ("question_text", "pub_date") VALUES (%(0)s, %(1)s)
Pymongo error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: polls1.polls_question index: __primary_key__ dup key: { : 1 }', 'op': {'id': 1, 'question_text': 'test2', 'pub_date': datetime.datetime(2019, 3, 31, 2, 40, 42), '_id': ObjectId('5ca028ac841ed81c72bfe500')}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}
Version: 1.2.32
```

#### tried fixing using

`python manage.py sqlsequencereset polls`

**Comment by d6tdev** [comment]
nvm found it `db['__schema__'].update_one({'name':'polls_question'},{ "$set": {'auto': {'field_names': ['id'], 'seq': 4}}})`

**Comment by iserranoe** [comment]
I am having this very same problem after restoring my mongo database with Mongorestore, Djongo wants to create a duplicated id. I don't get how you solved it, I guess it is a problem of Djongo?

**Comment by aforeverit** [comment]
Hello All, 
Even I am also facing same issue after migrating sample data from one db to another db. How to increment sequence?

Please suggest.

Thanks
Nagaraju

**Comment by iserranoe** [comment]
My problem, using MongoDB, was that I hadn't migrated the whole database, just a collection. I had to migrate the whole database because in the __schema__ is all information about id's.
