### ISSUE TITLE
I want to stop the creation of id field in the documents. How can I do that?

### ISSUE THREAD

**Issue by codhia** [nesdis/djongo#268]
How to stop the creation of id field automatically?

**Comment by thestick613** [comment]
delegate another field in the model to be the primary key, with primary_key=True

**Comment by codhia** [comment]
I've already done that made the _id key as primary in the model, but the id field is still getting added and the increment is still happening. I have run the makemigrations and migrate as well

**Comment by thestick613** [comment]
add both primary_key=True, and db_collumn="_id".

**Comment by codhia** [comment]
still did not work, was the collumn with 2 lls? I tried with a single l.

**Comment by thestick613** [comment]
db_column='_id', primary_key=True, one L, my bad.

**Comment by thestick613** [comment]
MongoDB documents will always have an _id field, you cannot remove it.

**Comment by shaikhhafizf** [comment]
> How to stop the creation of id field automatically?

In my Case the id field is not genrating automatically, Is there any solution

>>> user = TestModel(unit='check')                    
>>> user.save()
>>> user.id
ObjectId('5f5715f73cbe86ac869e25f8')
>>> user = TestModel.objects.filter(unit='check') 
>>> user
<QuerySet [<TestModel: TestModel object (None)>]>
>>> print(user[0].id)
None
![image](https://user-images.githubusercontent.com/59253733/92438318-34cead00-f1c6-11ea-87fc-366935c2e50e.png)
