### ISSUE TITLE
DISTINCT: SQLDecodeError 

### ISSUE THREAD

**Issue by ayakut** [nesdis/djongo#27]
Hi guys,

#### One line description of the issue
When the Djongo tries to convert next SQL:
> **SELECT DISTINCT "viewflow_task"."flow_task" FROM "viewflow_task" INNER JOIN "viewflow_process" ON ("viewflow_task"."process_id" = "viewflow_process"."id") WHERE ("viewflow_process"."flow_class" IN (%(0)s, %(1)s, %(2)s) AND "viewflow_task"."owner_id" = %(3)s AND "viewflow_task"."status" = %(4)s) ORDER BY "viewflow_task"."flow_task" ASC**

it raises exception SQLDecodeError

#### Python script

```pthon : in the djongo/sql2mongo.py
...
class SQLToken:
...
    @classmethod
    def iter_tokens(cls, token):
...
_#it happens here_
        elif token.match(tokens.Keyword, 'NULL'):
            yield None
        else:
            **raise SQLDecodeError**
```

#### Traceback
> Request Method: | GET
-- | --
http://127.0.0.1:8000/workflow/
1.11.7
SQLDecodeError
c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in iter_tokens, line 655
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe
3.6.2
['C:/Users/alexk/development/projects/python/fifa_mongo',  'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',  'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo',  'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',  'C:\\Users\\alexk\\.PyCharm2017.3\\system\\cythonExtensions',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\Scripts\\python36.zip',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\DLLs',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\lib',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\setuptools-28.8.0-py3.6.egg',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\pip-9.0.1-py3.6.egg',  'c:\\users\\alexk\\development\\projects\\python\\djongo',  'C:\\Program Files\\JetBrains\\PyCharm '  '2017.2.3\\helpers\\pycharm_matplotlib_backend',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\IPython\\extensions',  'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo']
Wed, 6 Dec 2017 13:05:58 +0000

**Comment by nesdis** [comment]
The sql you show above is it raw sql or something generated by an app?

Which app is generating this?

**Comment by ayakut** [comment]
Hi @nesdis ,

The sql was generated by the ViewFlow app. [()](https://github.com/viewflow/viewflow)

**Comment by nesdis** [comment]
This is not too hard to implement will post an update soon.

**Comment by ayakut** [comment]
Hi @nesdis ,

It sounds great to me!
Thanks a lot!

**Comment by nesdis** [comment]
I have pushed a commit. but it is not fully tested, however you may want to check if it works for you

**Comment by ayakut** [comment]
Hi @nesdis ,

Thanks for the update.
Sure, I'll check it and will update you on results.

**Comment by ayakut** [comment]
Hi @nesdis ,

The isse is not solved. Below details.
Original SQL:
> SELECT "viewflow_process"."id", "viewflow_process"."flow_class", "viewflow_process"."status", "viewflow_process"."created", "viewflow_process"."finished" FROM "viewflow_process" WHERE "viewflow_process"."id" IN (SELECT U0."process_id" AS Col1 FROM "viewflow_task" U0 INNER JOIN "viewflow_process" U1 ON (U0."process_id" = U1."id") WHERE (U1."flow_class" IN (%(0)s, %(1)s, %(2)s) AND U0."owner_id" = %(3)s AND U0."status" = %(4)s)) ORDER BY "viewflow_process"."created" DESC

Processed SQL:
> (SELECT U0."process_id" AS Col1 FROM "viewflow_task" U0 INNER JOIN "viewflow_process" U1 ON (U0."process_id" = U1."id") WHERE (U1."flow_class" IN (%(0)s, %(1)s, %(2)s) AND U0."owner_id" = %(3)s AND U0."status" = %(4)s))

Python code raised the exception:
```in /djongo/sql2mongo.py, row # 692
        elif token.match(tokens.Name.Placeholder, '.*', regex=True):
            index = int(re.match(r'%\(([0-9]+)\)s', token.value, flags=re.IGNORECASE).group(1))
            yield index

        elif token.match(tokens.Keyword, 'NULL'):
            yield None
        else:
            raise SQLDecodeError

    def to_mongo(self):
        raise SQLDecodeError #HERE


class EqToken(SQLToken):
```

Django's report:
> Request Method: | GET
-- | --
http://127.0.0.1:8000/workflow/
1.11.7
SystemError
error return without exception set
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\template\context.py in push_state, line 224
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe
3.6.2
['C:/Users/alexk/development/projects/python/fifa_mongo',  'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',  'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo',  'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',  'C:\\Users\\alexk\\.PyCharm2017.3\\system\\cythonExtensions',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\Scripts\\python36.zip',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\DLLs',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\lib',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\setuptools-28.8.0-py3.6.egg',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\pip-9.0.1-py3.6.egg',  'c:\\users\\alexk\\development\\projects\\python\\djongo',  'C:\\Program Files\\JetBrains\\PyCharm '  '2017.2.3\\helpers\\pycharm_matplotlib_backend',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\IPython\\extensions',  'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo']
Thu, 7 Dec 2017 06:30:38 +0000

**Comment by nesdis** [comment]
so is this your failing SQL? :

SELECT "viewflow_process"."id", "viewflow_process"."flow_class", "viewflow_process"."status", "viewflow_process"."created", "viewflow_process"."finished" FROM "viewflow_process" WHERE "viewflow_process"."id" IN (SELECT U0."process_id" AS Col1 FROM "viewflow_task" U0 INNER JOIN "viewflow_process" U1 ON (U0."process_id" = U1."id") WHERE (U1."flow_class" IN (%(0)s, %(1)s, %(2)s) AND U0."owner_id" = %(3)s AND U0."status" = %(4)s)) ORDER BY "viewflow_process"."created" DESC

It has a 'SELECT inside another SELECT' so that is like a really complex SQL query. There is no yet support for such high level nestings yet...

**Comment by ayakut** [comment]
Hi @nesdis ,

The SQL had been generated by the ViewFlow app.
It seems like during SQL parsing the Djongo meets included SELECT in the SQL and can't process it...

**Comment by nesdis** [comment]
Statement 1: 
```
SELECT "viewflow_process"."id", "viewflow_process"."flow_class", "viewflow_process"."status", "viewflow_process"."created", "viewflow_process"."finished" FROM "viewflow_process" WHERE "viewflow_process"."id" IN (SELECT U0."process_id" AS Col1 FROM "viewflow_task" U0 INNER JOIN "viewflow_process" U1 ON (U0."process_id" = U1."id") WHERE (U1."flow_class" IN (%(0)s, %(1)s, %(2)s) AND U0."owner_id" = %(3)s AND U0."status" = %(4)s)) ORDER BY "viewflow_process"."created" DESC
```
Statement 2:
```
(SELECT U0."process_id" AS Col1 FROM "viewflow_task" U0 INNER JOIN "viewflow_process" U1 ON (U0."process_id" = U1."id") WHERE (U1."flow_class" IN (%(0)s, %(1)s, %(2)s) AND U0."owner_id" = %(3)s AND U0."status" = %(4)s))
```

Which one is having trouble parsing 1 or 2 or both?

**Comment by ayakut** [comment]
Hi @nesdis ,

It looks like the DISTINCT issue is solved.

NESTED SELECT is likely the next issue...

**Comment by nesdis** [comment]
According to the [Django docs](https://docs.djangoproject.com/en/dev/ref/models/querysets/#in) nested quieries are not very efficient. It sometimes makes sense to do 2 queries instead of nesting. 

While it is possible to translate nested queries to query documents, it is still not implemented. It will take a while to implement this. At the same time you may consider executing the inner query first, then passing the result to the outer query.

**Comment by ayakut** [comment]
Hi @nesdis ,

Thanks for the update.
I use the ViewFlow app as an external app and can't change it...

**Comment by nesdis** [comment]
There is now support for handling nested SQL queries.... You may want to clone the latest commit to check if the viewflow app works. All the changes have not been tested fully though.

**Comment by ayakut** [comment]
Hi @nesdis ,

Thanks a lot for the update!
I'll check how this version works on my side!

**Comment by nesdis** [comment]
Since there is now support for SQL nested queries, I will close this issue.

**Comment by ayakut** [comment]
Hi @nesdis ,

Thanks a lot for your job!
