### ISSUE TITLE
Cannot migrate field names 

### ISSUE THREAD

**Issue by eunos-1128** [nesdis/djongo#283]
I tried to change field names by `python manage.py migrate` but it resulted in unchanged field names. 

djongo v1.2.31
Django v2.1.
MongoDB v4.0.10

```python
summaryID = models.PositiveSmallIntegerField(null=True, blank=True)
summary_id =  models.PositiveSmallIntegerField(null=True, blank=True)
```
The field name is still be 'summaryID'.

**Comment by JRose6** [comment]
I've had this issue before as well, my solution is usually to update them manually in mongo.

**Comment by eunos-1128** [comment]
I updated it manually and it worked well.
Thanks.
