### ISSUE TITLE
SELECT COUNT(*) FROM (SELECT "entities_entity"."_id" AS Col1 FROM "entities_entity"  LIMIT 26) subquery

### ISSUE THREAD

**Issue by vaimdev** [nesdis/djongo#284]
Subquery is not handled properly, SQLDecodeError is thrown

```SQL
SELECT COUNT(*) FROM (SELECT "entities_entity"."_id" AS Col1 FROM "entities_entity"  LIMIT 26) subquery
```

**Comment by vaimdev** [comment]
This is a strange SQL generated from django. 
After I restructure my django code, this SQL is not generated anymore, hence, no more such issue.
I'll close this issue but I really would like to know whether djongo support subquery or not? As I traced into the code, it seems like not supporting subquery.

**Comment by ronpetit** [comment]
I'm having this issue, and even removing the subquery from SQL give me the error, I think the problem is related to the count operation along with a limit, I can even reproduce it in shell by doing

```python
Video.objects.all().order_by('-creation_date')[:6].count()
```
