### ISSUE TITLE
iexact and other keywords not workin

### ISSUE THREAD

**Issue by vigneshwarancontus** [nesdis/djongo#29]
Please update for 'LIKE' Query too.
Request Method: | GET
-- | --
http://127.0.0.1:8000/student_module/login_user
1.11.7
AttributeError
'NoneType' object has no attribute 'lhs'
/home/user/vky/lib/python3.6/site-packages/djongo/sql2mongo.py in __init__, line 975
/home/user/vky/bin/python
3.6.3
['/home/user/projvky/projvky_mongo',  '/home/user/vky/lib/python36.zip',  '/home/user/vky/lib/python3.6',  '/home/user/vky/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/user/vky/lib/python3.6/site-packages']
Mon, 11 Dec 2017 10:56:12 +0000

**Comment by nesdis** [comment]
Like query needs to be implemented using `$regex` operator in MongoDB. Not all SQL operators introduced by different SQL vendors can be implemented in MongoDB. Eg in SQLLite iexact will only work on ASCII characters. As of now there is no plan to support those minor SQL operators that are not supported widely.

**Comment by tbobm** [comment]
Even though different SQL vendors provide a non-uniform set of feature, what could go wrong if text operations would happen to be implemented in `djongo` ? I could probably find the time to make a PR and implement some missing operators, such as the ones I mentionned in #39 .

It would be a pleasure to work on your project, and because the target is actually MongoDB, I don't see any issue (correct me if I'm wrong) with implementing this kind of features in `djongo`.

**Comment by nesdis** [comment]
Great go-ahead. You will have a special mention on the home-page!

As a starter, all the operators mentioned in #39 can be implemented using MongoDB regex operators. 

Take a look at `djongo/base.py` call that inherits from `BaseDatabaseWrapper` class.
Django operators (eg., `exact` , `contains` etc.,) will have to be mapped to any other keyword (You can decide what keyword you want to map it to, for now it maps to default SQL keywords of LIKE, REGEXP)

Next, in `sql2mongo.py` define a new `Op` class and do the needful.

The branch `iexact_support` has this implementation partially underway.

**Comment by nesdis** [comment]
There is now code for LIKE operator. @tbobm you can pull this code and check if it works for you. It has not been tested fully though

**Comment by nesdis** [comment]
@vigneshwarancontus You can check if this works for you now

**Comment by nesdis** [comment]
The new feature has been tested. Closing this

**Comment by HugoSPT** [comment]
I know this is closed but shouldn't the `to_match` string be escaped in `LikeOp _make_regex?` Otherwise special chars won't work when passed by to Mongo query as `$regex`
