### ISSUE TITLE
int() argument must be a string, a bytes-like object or a number, not 'ObjectId'

### ISSUE THREAD

**Issue by Rockflo** [nesdis/djongo#298]
Well I may have missed something there (django/Mongo beginner) but I could not find any way to serialize my ObjectIdField (see the error in the issue name). How could I identifier my entities on the client side then ? Regards

**Comment by Pheelbert** [comment]
I'm also seeing this issue when trying to run my web app in a docker container. Let me know if I can share any useful information for debugging!

**Comment by SomeoneInParticular** [comment]
@Rockflo and @Pheelbert; by serializer do you mean w/ Django REST serializers, or some other form of serialization?

**Comment by Pheelbert** [comment]
Actually the issue for me was that I had an old migrations folder in my repository that was getting itself into the container image which later was getting `python ./manage.py migrate`'ed at startup. Afterwards, when we would try to pull the MongoDB documents from mongo into the Django ORM, we would get this error you described when using the ORMObject.save() function. So, the trick is to completely wipe out the database (if that's an option for you, lol), or clean the ./migrations/ folder (possibly even remove entries for you app in the django_migrations collection of the data database), and then try pulling the data again (or whatever you're trying to do).

**Comment by SomeoneInParticular** [comment]
Oh; well them, fingers crossed it works for @Rockflo

**Comment by Rockflo** [comment]
> @Rockflo and @Pheelbert; by serializer do you mean w/ Django REST serializers, or some other form of serialization?

Thank you very much for your help. Yes indeed I use Django Rest Framework. So I tried again by:
- wiping out the database
- removing the ./migrations/ folder
- running again `manage.py makemigrations <app_name>` and ` manage.py migrate`

Unfortunately I still encounter this problem (same message). I am using an Anaconda distribution on Windows. Here is my serializers.py... I am not able to serialize the "CurveConfiguration" id.
[serializers.py.txt](https://github.com/nesdis/djongo/files/3441299/serializers.py.txt)

**Comment by raghava-k2** [comment]
Hi I am also facing the similar issue.I the ObjectId field is not able to serialize using Django rest framework.Is there any work around to resolve this issue?

**Comment by SomeoneInParticular** [comment]
Hello @Rockflo and @raghava-k2; Basically, under the hood, Django REST is trying to interpret a field it doesn't natively understand into an integer (its default means of trying to resolve these issues). To fix this error, you will have to do one of the following to allow the REST serializer to process ObjectID fields in your model:

1. Implement a custom serializer field to handle ObjectID fields. An example of this implementation is below (you can customize it more as well, if you'd prefer):
```python
# MongoDB codex packages; should be available in most python distributions
from bson import ObjectID
from bson.errors import InvalidID
...
class ObjectIdField(serializers.Field):
    """ Serializer field for Djongo ObjectID fields """
    def to_internal_value(self, data):
        # Serialized value -> Database value
        try:
            return ObjectId(str(data))  # Get the ID, then build an ObjectID instance using it
        except InvalidId:
            raise serializers.ValidationError(
                '`{}` is not a valid ObjectID'.format(data)

    def to_representation(self, value):
        # Database value -> Serialized value
        if not ObjectId.is_valid(value):  # User submitted ID's might not be properly structured
            raise InvalidId
        return smart_text(value)
...
class YourModelSerializer(ModelSerializer):
    _id = ObjectIdField(read_only=True)

    class Meta:
        model = YourModel
        fields = '__all__'
```
2. If you'll apologize the shill, you can use my package, `rest-meets-djongo`, and use the DjongoModelSerializer as the base for your model serializer (rather than ModelSerializer); it will automatically generate default implementations of serializers for Model's w/ Djongo-based fields (ObjectIdField, EmbeddedModelField, ArrayModelField etc.); you can also just use my implementation of ObjectIdField provided therein. An example implementation:
```python
from rest_meets_djongo.serializers import DjongoModelSerializer

class YourModelSerializer(DjongoModelSerializer):
    class Meta:
        model = YourModel
        fields = '__all__'
```
(The package is not quite complete as of writing (ArrayReferenceFields are currently handled rather unusually, I'm working on it), and lacks formal documentation (this weeks task for me!), but for the most part it functions exactly like you would expect a ModelSerializer to work in Django REST; if you choose to use it, please report issues here: https://gitlab.com/SomeoneInParticular/rest_meets_djongo/issues. I'll be adding a GitHub mirror soon as well)

**Comment by Rockflo** [comment]
I just tried to use the `rest-meets-djongo` package as you suggested and it did the trick ! Thank you very much @SomeoneInParticular

**Comment by raghava-k2** [comment]
> Hello @Rockflo and @raghava-k2; Basically, under the hood, Django REST is trying to interpret a field it doesn't natively understand into an integer (its default means of trying to resolve these issues). To fix this error, you will have to do one of the following to allow the REST serializer to process ObjectID fields in your model:
> 
> 1. Implement a custom serializer field to handle ObjectID fields. An example of this implementation is below (you can customize it more as well, if you'd prefer):
> 
> ```python
> # MongoDB codex packages; should be available in most python distributions
> from bson import ObjectID
> from bson.errors import InvalidID
> ...
> class ObjectIdField(serializers.Field):
>     """ Serializer field for Djongo ObjectID fields """
>     def to_internal_value(self, data):
>         # Serialized value -> Database value
>         try:
>             return ObjectId(str(data))  # Get the ID, then build an ObjectID instance using it
>         except InvalidId:
>             raise serializers.ValidationError(
>                 '`{}` is not a valid ObjectID'.format(data)
> 
>     def to_representation(self, value):
>         # Database value -> Serialized value
>         if not ObjectId.is_valid(value):  # User submitted ID's might not be properly structured
>             raise InvalidId
>         return smart_text(value)
> ...
> class YourModelSerializer(ModelSerializer):
>     _id = ObjectIdField(read_only=True)
> 
>     class Meta:
>         model = YourModel
>         fields = '__all__'
> ```
> 
> 1. If you'll apologize the shill, you can use my package, `rest-meets-djongo`, and use the DjongoModelSerializer as the base for your model serializer (rather than ModelSerializer); it will automatically generate default implementations of serializers for Model's w/ Djongo-based fields (ObjectIdField, EmbeddedModelField, ArrayModelField etc.); you can also just use my implementation of ObjectIdField provided therein. An example implementation:
> 
> ```python
> from rest_meets_djongo.serializers import DjongoModelSerializer
> 
> class YourModelSerializer(DjongoModelSerializer):
>     class Meta:
>         model = YourModel
>         fields = '__all__'
> ```
> 
> (The package is not quite complete as of writing (ArrayReferenceFields are currently handled rather unusually, I'm working on it), and lacks formal documentation (this weeks task for me!), but for the most part it functions exactly like you would expect a ModelSerializer to work in Django REST; if you choose to use it, please report issues here: https://gitlab.com/SomeoneInParticular/rest_meets_djongo/issues. I'll be adding a GitHub mirror soon as well)

Thanks for providing the work around.It works like butter..

**Comment by eunos-1128** [comment]
> Hello @Rockflo and @raghava-k2; Basically, under the hood, Django REST is trying to interpret a field it doesn't natively understand into an integer (its default means of trying to resolve these issues). To fix this error, you will have to do one of the following to allow the REST serializer to process ObjectID fields in your model:
> 
> 1. Implement a custom serializer field to handle ObjectID fields. An example of this implementation is below (you can customize it more as well, if you'd prefer):
> 
> ```python
> # MongoDB codex packages; should be available in most python distributions
> from bson import ObjectID
> from bson.errors import InvalidID
> ...
> class ObjectIdField(serializers.Field):
>     """ Serializer field for Djongo ObjectID fields """
>     def to_internal_value(self, data):
>         # Serialized value -> Database value
>         try:
>             return ObjectId(str(data))  # Get the ID, then build an ObjectID instance using it
>         except InvalidId:
>             raise serializers.ValidationError(
>                 '`{}` is not a valid ObjectID'.format(data)
> 
>     def to_representation(self, value):
>         # Database value -> Serialized value
>         if not ObjectId.is_valid(value):  # User submitted ID's might not be properly structured
>             raise InvalidId
>         return smart_text(value)
> ...
> class YourModelSerializer(ModelSerializer):
>     _id = ObjectIdField(read_only=True)
> 
>     class Meta:
>         model = YourModel
>         fields = '__all__'
> ```
> 
> 1. If you'll apologize the shill, you can use my package, `rest-meets-djongo`, and use the DjongoModelSerializer as the base for your model serializer (rather than ModelSerializer); it will automatically generate default implementations of serializers for Model's w/ Djongo-based fields (ObjectIdField, EmbeddedModelField, ArrayModelField etc.); you can also just use my implementation of ObjectIdField provided therein. An example implementation:
> 
> ```python
> from rest_meets_djongo.serializers import DjongoModelSerializer
> 
> class YourModelSerializer(DjongoModelSerializer):
>     class Meta:
>         model = YourModel
>         fields = '__all__'
> ```
> 
> (The package is not quite complete as of writing (ArrayReferenceFields are currently handled rather unusually, I'm working on it), and lacks formal documentation (this weeks task for me!), but for the most part it functions exactly like you would expect a ModelSerializer to work in Django REST; if you choose to use it, please report issues here: https://gitlab.com/SomeoneInParticular/rest_meets_djongo/issues. I'll be adding a GitHub mirror soon as well)

@SomeoneInParticular 
Thank you for your work. I have just faced the same problem and tried to use interger id instead of  Object ID, which didnot work. Using your package solved this problem in a moment. Awesome!

**Comment by JosiahDub** [comment]
I dealt with this issue just now and noticed that the schema for my model (`auth_user` in my case) had not been added to the `__schema__` collection. Most other schemas had been added. I had another database with the correct schema so I copied the doc and it worked.

Any reason why the `auth_user` schema wouldn't be uploaded during migration?

**Comment by SomeoneInParticular** [comment]
@JosiahDub sorry for the delay; I left on holiday shortly before you posted and only recently got back into the swing of things. 

I genuinely could not replicate your scenario despite my best efforts, with or without the workarounds above. Could you provide example code or the like for review?

**Comment by JosiahDub** [comment]
> @JosiahDub sorry for the delay; I left on holiday shortly before you posted and only recently got back into the swing of things.
> 
> I genuinely could not replicate your scenario despite my best efforts, with or without the workarounds above. Could you provide example code or the like for review?

My particular problem was probably from inexperience. I haven't had an issue since then.

**Comment by iambhushan6** [comment]
I am facing this issue my instance is not saving with id and throws this error all the time

**Comment by henriqueblobato** [comment]
import djongo instead and add the id_ field at the model

```
from djongo import models

class Subject(models.Model):
    _id = models.ObjectIdField()
    ...
```
