### ISSUE TITLE
admin not working

### ISSUE THREAD

**Issue by gurugeek** [nesdis/djongo#3]
I did reinstall and as I can't see the data being fetched I tried to enter the admin but it doesn't seem to work:
"

Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/login/?next=/admin/
1.11.4
ValueError
Cannot force an update in save() with no primary key.
/Users/doctorstrange/django/environments/my_env/lib/python3.6/site-packages/django/db/models/base.py in _save_table, line 895
/Users/doctorstrange/django/environments/my_env/bin/python
3.6.2
"

apologies in advance if is a mistake at my end..

**Comment by nesdis** [comment]
This does not appear to be related to djongo. Looks like you are trying to save a model without selecting the primary key in admin. 

Do you get this error if you perform the same steps with MySQL connector??

**Comment by gurugeek** [comment]
solved now thanks! No this error did not happen with MySQL because Django automatically adds the "id" field that is a primary key.  Now all works also the admin! I had to run migrations and change db but all seems to work. Thanks again, this is a wonderful library with a lot of potential.

**Comment by nesdis** [comment]
You can recommend this library to other users in your field as well.,.. The idea is to make django and mongodb usage seamless.

**Comment by miphilomath** [comment]
For someone facing the same problem in future. I faced the same problem and resolved it by changing the Database name to a new one from 'admin'. Then, make the migrations again './manage.py makemigrations'  and './manage.py migrate'. 
This created the required internal schema which was not there and hence the error.

**Comment by towen** [comment]
Hi, I'm having this issue also.
I tried changing my database name:
```
DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE' : 'djongo',
        'NAME'   : 'djongoTestDB'
    }
}
```
I changed djongoTestDB to djongoTestDB2, and then made and ran the migrations. No changes detected? and still borked.
Is there a different database name I need to change somewhere?

**Comment by Jesuszilla** [comment]
> For someone facing the same problem in future. I faced the same problem and resolved it by changing the Database name to a new one from 'admin'. Then, make the migrations again './manage.py makemigrations' and './manage.py migrate'. This created the required internal schema which was not there and hence the error.

How do you do this? I don't understand what you mean when you say "changing the database name to a new one from 'admin'" how do you do that?

My `DATABASES` looks like:
```
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'jesuszillaslawn',
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': os.environ['BACKYARD_URI']
        }
    }
}
```

**Comment by wjingen** [comment]
> > For someone facing the same problem in future. I faced the same problem and resolved it by changing the Database name to a new one from 'admin'. Then, make the migrations again './manage.py makemigrations' and './manage.py migrate'. This created the required internal schema which was not there and hence the error.
> 
> How do you do this? I don't understand what you mean when you say "changing the database name to a new one from 'admin'" how do you do that?
> 
> My `DATABASES` looks like:
> 
> ```
> DATABASES = {
>     'default': {
>         'ENGINE': 'djongo',
>         'NAME': 'jesuszillaslawn',
>         'ENFORCE_SCHEMA': False,
>         'CLIENT': {
>             'host': os.environ['BACKYARD_URI']
>         }
>     }
> }
> ```

Simply change your NAME from "jesuszillaslawn" to something else, such as "jesuszillaslawn2".

**Comment by boxxello** [comment]
> For someone facing the same problem in future. I faced the same problem and resolved it by changing the Database name to a new one from 'admin'. Then, make the migrations again './manage.py makemigrations' and './manage.py migrate'. This created the required internal schema which was not there and hence the error.

Ran ./manage.py makemigrations and then ./manage.py migrate --fake , then I created the superuser with a non-default username and it did it for me!

Adding this to the closed issue because it might help someone out!

**Comment by jDimmy** [comment]
It works for me. Thanks

**Comment by AniketRajSingh** [comment]
python manage.py migrate admin
python manage.py migrate auth
python manage.py migrate contenttypes
python manage.py migrate sessions

 DO THEM SEPARATELY, IF THE PREVIOUS SOLUTION DIDN'T WORK

**Comment by ronfromhp** [comment]
can someone please give me a solution that doesnt involve having to nuke my entire database?
