### ISSUE TITLE
SQLDecodeError at /admin/testapp/studentdetail/add/

### ISSUE THREAD

**Issue by phileinSophos** [nesdis/djongo#329]
FAILED SQL: INSERT INTO "StudentDetail" ("s_roll", "s_name", "s_address", "s_marks") VALUES (%(0)s, %(1)s, %(2)s, %(3)s)

Params: [22, 'shahrukh', 'delhi', 33]

Pymongo error: {'writeErrors': [{'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: RuleEngine.StudentDetail index: __primary_key__ dup key: { : null }', 'op': {'s_roll': 22, 's_name': 'shahrukh', 's_address': 'delhi', 's_marks': 33, '_id': ObjectId('5db0536c57bb29e9ccfd2826')}}], 'writeConcernErrors': [], 'nInserted': 0, 'nUpserted': 0, 'nMatched': 0, 'nModified': 0, 'nRemoved': 0, 'upserted': []}

**Comment by Parshwa27** [comment]
Hello, were you able to find any solution to this? I am facing the same issue while trying to add tokens via simplejwt
