### ISSUE TITLE
AttributeError: UpdateQuery object has no attribute alias2op

### ISSUE THREAD

**Issue by ayakut** [nesdis/djongo#33]
Hi @nesdis ,

When I've entered my login/password and press button "LOG IN", the system response me with an error.

Here is the response:
> AttributeError at /accounts/login/
'UpdateQuery' object has no attribute 'alias2op'
Request Method:	POST
Request URL:	http://127.0.0.1:8000/accounts/login/?next=/workflow/
Django Version:	1.11.7
Exception Type:	AttributeError
Exception Value:	
'UpdateQuery' object has no attribute 'alias2op'
Exception Location:	c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in _identifier, line 191
Python Executable:	C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe
Python Version:	3.6.2
Python Path:	
['C:/Users/alexk/development/projects/python/fifa_mongo',
 'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',
 'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo',
 'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',
 'C:\\Users\\alexk\\.PyCharm2017.3\\system\\cythonExtensions',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\Scripts\\python36.zip',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\DLLs',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\lib',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\setuptools-28.8.0-py3.6.egg',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\pip-9.0.1-py3.6.egg',
 'c:\\users\\alexk\\development\\projects\\python\\djongo',
 'C:\\Program Files\\JetBrains\\PyCharm '
 '2017.2.3\\helpers\\pycharm_matplotlib_backend',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo']
Server time:	Tue, 19 Dec 2017 06:48:00 +0000

I've debugged it and figured out that the issue happens in the sql2mongo.py at row #191 when we try to parse following statement:
```
UPDATE` "auth_user" SET "last_login" = %(0)s WHERE "auth_user"."id" = %(1)s
```

**Comment by nesdis** [comment]
I have pushed a change, please check

**Comment by nesdis** [comment]
@ayakut the issue has been fixed... Do i close this ticket?

**Comment by ayakut** [comment]
Hi @nesdis ,

Thanks for the update.
Please, let me check it. I will update you nearest time about a result.

**Comment by ayakut** [comment]
Hi @nesdis ,,

I've pulled your updates.
Now it raises next exception
>OperationFailure at /workflow/
Invalid $project specification: specification must have at least one field
Request Method:	GET
Request URL:	http://127.0.0.1:8000/workflow/
Django Version:	1.11.7
Exception Type:	OperationFailure
Exception Value:	
Invalid $project specification: specification must have at least one field
Exception Location:	C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\helpers.py in _check_command_response, line 210
Python Executable:	C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe
Python Version:	3.6.2
Python Path:	
['C:/Users/alexk/development/projects/python/fifa_mongo',
 'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',
 'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo',
 'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',
 'C:\\Users\\alexk\\.PyCharm2017.3\\system\\cythonExtensions',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\Scripts\\python36.zip',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\DLLs',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\lib',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\setuptools-28.8.0-py3.6.egg',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\pip-9.0.1-py3.6.egg',
 'c:\\users\\alexk\\development\\projects\\python\\djongo',
 'C:\\Program Files\\JetBrains\\PyCharm '
 '2017.2.3\\helpers\\pycharm_matplotlib_backend',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo']
Server time:	Tue, 19 Dec 2017 16:46:55 +0000

Parsed query looks so:
>c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in _get_cursor
            cur = self._result_ref.db[self.left_table].aggregate(pipeline) ...
▼ Local vars
Variable	Value
join	
<djongo.sql2mongo.InnerJoinConverter object at 0x000001922DAD9AC8>
pipeline	
[{'$match': {'process_id': {'$exists': True, '$ne': None}}},
 {'$lookup': {'as': 'viewflow_process',
              'foreignField': 'id',
              'from': 'viewflow_process',
              'localField': 'process_id'}},
 {'$unwind': '$viewflow_process'},
 {'$match': {'$and': [{'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                               'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                               'flows/flows.hotel_mapping.ProviderScan']}},
                      {'owner_id': {'$eq': 1}},
                      {'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                               'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                               'flows/flows.hotel_mapping.ProviderScan']}},
                      {'owner_id': {'$eq': 1}},
                      {'status': {'$eq': 'ASSIGNED'}},
                      {'status': {'$eq': 'ASSIGNED'}}]}},
 {'$sort': OrderedDict([('flow_task', 1)])},
 {'$project': {}}]
self	
<djongo.sql2mongo.SelectQuery object at 0x000001922DA7F128>

and further:
>C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\collection.py in aggregate
                                           collation=collation) ...
▼ Local vars
Variable	Value
batch_size	
None
cmd	
{'aggregate': 'viewflow_task',
 'cursor': {},
 'pipeline': [{'$match': {'process_id': {'$exists': True, '$ne': None}}},
              {'$lookup': {'as': 'viewflow_process',
                           'foreignField': 'id',
                           'from': 'viewflow_process',
                           'localField': 'process_id'}},
              {'$unwind': '$viewflow_process'},
              {'$match': {'$and': [{'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                                            'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                                            'flows/flows.hotel_mapping.ProviderScan']}},
                                   {'owner_id': {'$eq': 1}},
                                   {'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                                            'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                                            'flows/flows.hotel_mapping.ProviderScan']}},
                                   {'owner_id': {'$eq': 1}},
                                   {'status': {'$eq': 'ASSIGNED'}},
                                   {'status': {'$eq': 'ASSIGNED'}}]}},
              {'$sort': OrderedDict([('flow_task', 1)])},
              {'$project': {}}]}
collation	
None
dollar_out	
False
kwargs	
{'cursor': {}}
pipeline	
[{'$match': {'process_id': {'$exists': True, '$ne': None}}},
 {'$lookup': {'as': 'viewflow_process',
              'foreignField': 'id',
              'from': 'viewflow_process',
              'localField': 'process_id'}},
 {'$unwind': '$viewflow_process'},
 {'$match': {'$and': [{'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                               'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                               'flows/flows.hotel_mapping.ProviderScan']}},
                      {'owner_id': {'$eq': 1}},
                      {'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                               'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                               'flows/flows.hotel_mapping.ProviderScan']}},
                      {'owner_id': {'$eq': 1}},
                      {'status': {'$eq': 'ASSIGNED'}},
                      {'status': {'$eq': 'ASSIGNED'}}]}},
 {'$sort': OrderedDict([('flow_task', 1)])},
 {'$project': {}}]
self	
Collection(Database(MongoClient(host=['dev-hybrid-mongodb-service-us:27017'], document_class=collections.OrderedDict, tz_aware=False, connect=True), 'fifa_mongo'), 'viewflow_task')
slave_ok	
False
sock_info	
SocketInfo(<socket.socket fd=2248, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.1.13.92', 51595), raddr=('10.200.137.84', 27017)>) at 1727340991656
use_cursor	
True

and futher
>C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\collection.py in _command
            collation=collation) ...
▼ Local vars
Variable	Value
allowable_errors	
None
check	
True
codec_options	
None
collation	
None
command	
{'aggregate': 'viewflow_task',
 'cursor': {},
 'pipeline': [{'$match': {'process_id': {'$exists': True, '$ne': None}}},
              {'$lookup': {'as': 'viewflow_process',
                           'foreignField': 'id',
                           'from': 'viewflow_process',
                           'localField': 'process_id'}},
              {'$unwind': '$viewflow_process'},
              {'$match': {'$and': [{'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                                            'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                                            'flows/flows.hotel_mapping.ProviderScan']}},
                                   {'owner_id': {'$eq': 1}},
                                   {'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                                            'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                                            'flows/flows.hotel_mapping.ProviderScan']}},
                                   {'owner_id': {'$eq': 1}},
                                   {'status': {'$eq': 'ASSIGNED'}},
                                   {'status': {'$eq': 'ASSIGNED'}}]}},
              {'$sort': OrderedDict([('flow_task', 1)])},
              {'$project': {}}]}
parse_write_concern_error	
False
read_concern	
ReadConcern()
read_preference	
None
self	
Collection(Database(MongoClient(host=['dev-hybrid-mongodb-service-us:27017'], document_class=collections.OrderedDict, tz_aware=False, connect=True), 'fifa_mongo'), 'viewflow_task')
slave_ok	
False
sock_info	
SocketInfo(<socket.socket fd=2248, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.1.13.92', 51595), raddr=('10.200.137.84', 27017)>) at 1727340991656
write_concern	
None


and further
>C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\pool.py in command
                           collation=collation) ...
▼ Local vars
Variable	Value
allowable_errors	
None
check	
True
check_keys	
False
codec_options	
CodecOptions(document_class=<class 'collections.OrderedDict'>, tz_aware=False, uuid_representation=PYTHON_LEGACY, unicode_decode_error_handler='strict', tzinfo=None)
collation	
None
dbname	
'fifa_mongo'
parse_write_concern_error	
False
read_concern	
ReadConcern()
read_preference	
Primary()
self	
SocketInfo(<socket.socket fd=2248, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.1.13.92', 51595), raddr=('10.200.137.84', 27017)>) at 1727340991656
slave_ok	
False
spec	
{'aggregate': 'viewflow_task',
 'cursor': {},
 'pipeline': [{'$match': {'process_id': {'$exists': True, '$ne': None}}},
              {'$lookup': {'as': 'viewflow_process',
                           'foreignField': 'id',
                           'from': 'viewflow_process',
                           'localField': 'process_id'}},
              {'$unwind': '$viewflow_process'},
              {'$match': {'$and': [{'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                                            'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                                            'flows/flows.hotel_mapping.ProviderScan']}},
                                   {'owner_id': {'$eq': 1}},
                                   {'viewflow_process.flow_class': {'$in': ['flows/flows.hotel_mapping.SingleHotelMapping',
                                                                            'flows/flows.main_onboarding.MainOnBoardingFlow',
                                                                            'flows/flows.hotel_mapping.ProviderScan']}},
                                   {'owner_id': {'$eq': 1}},
                                   {'status': {'$eq': 'ASSIGNED'}},
                                   {'status': {'$eq': 'ASSIGNED'}}]}},
              {'$sort': OrderedDict([('flow_task', 1)])},
              {'$project': {}}]}
write_concern	
None

and at the end
>C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\network.py in command
        unpacked = helpers._unpack_response(
            response, codec_options=codec_options)
        response_doc = unpacked['data'][0]
        if check:
            helpers._check_command_response(
                response_doc, None, allowable_errors,
                parse_write_concern_error=parse_write_concern_error) ...
    except Exception as exc:
        if publish:
            duration = (datetime.datetime.now() - start) + encoding_duration
            if isinstance(exc, (NotMasterError, OperationFailure)):
                failure = exc.details
            else:
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\helpers.py in _check_command_response
                raise DuplicateKeyError(errmsg, code, response)
            elif code == 50:
                raise ExecutionTimeout(errmsg, code, response)
            elif code == 43:
                raise CursorNotFound(errmsg, code, response)
            msg = msg or "%s"
            raise OperationFailure(msg % errmsg, code, response) ...
def _check_gle_response(response):
    """Return getlasterror response as a dict, or raise OperationFailure."""
    response = _unpack_response(response)
▼ Local vars
Variable	Value
allowable_errors	
None
code	
40177
details	
OrderedDict([('ok', 0.0),
             ('errmsg',
              'Invalid $project specification: specification must have at '
              'least one field'),
             ('code', 40177),
             ('codeName', 'Location40177')])
errmsg	
'Invalid $project specification: specification must have at least one field'
msg	
'%s'
parse_write_concern_error	
False
response	
OrderedDict([('ok', 0.0),
             ('errmsg',
              'Invalid $project specification: specification must have at '
              'least one field'),
             ('code', 40177),
             ('codeName', 'Location40177')])

**Comment by nesdis** [comment]
Can you print out the failing SQL as well?

**Comment by nesdis** [comment]
I have added some code to print the failing sql by default in case of exception. Please clone it otherwise and rerun the test. Thanks

**Comment by ayakut** [comment]
Hi @nesdis ,

OK, will do.

**Comment by ayakut** [comment]
Hi @nesdis ,

Look, you've added new printing to the function "def parse(self):", but my exception happens in another place of the code in the function "def _get_cursor(self):":
>"C:\Program Files\JetBrains\PyCharm 2017.2.3\bin\runnerw.exe" C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe "C:\Program Files\JetBrains\PyCharm 2017.2.3\helpers\pydev\pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 52552 --file C:/Users/alexk/development/projects/python/fifa_mongo/manage.py runserver 8000
pydev debugger: process 15424 is connecting
Connected to pydev debugger (build 173.3942.36)
pydev debugger: process 14328 is connecting
Performing system checks...
System check identified no issues (0 silenced).
December 20, 2017 - 08:32:42
Django version 1.11.7, using settings 'settings_dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2017-12-20 08:32:45 ERROR django.request ##: Internal Server Error: /workflow/
Traceback (most recent call last):
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\viewflow\compat.py", line 135, in _wrapper
    return bound_func(*args, **kwargs)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\viewflow\compat.py", line 131, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\material\frontend\views\list.py", line 353, in dispatch
    self.object_list = self.get_object_list()
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\material\frontend\views\list.py", line 386, in get_object_list
    self.filterset = self.get_filterset(filterset_class)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django_filters\views.py", line 35, in get_filterset
    return filterset_class(**kwargs)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\viewflow\frontend\filters.py", line 47, in __init__
    for task_ref in tasks]
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py", line 250, in __iter__
    self._fetch_all()
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py", line 152, in __iter__
    for row in compiler.results_iter():
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py", line 839, in results_iter
    for rows in results:
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py", line 1284, in cursor_iter
    sentinel):
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py", line 1283, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\utils.py", line 101, in inner
    return func(*args, **kwargs)
  File "c:\users\alexk\development\projects\python\djongo\djongo\cursor.py", line 50, in fetchmany
    ret.append(self.result.next())
  File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 738, in __next__
    return next(self._result_generator)
  File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 743, in __iter__
    yield from iter(self._query)
  File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 498, in __iter__
    self._cursor = self._get_cursor()
  File "c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py", line 547, in _get_cursor
    cur = self._result_ref.db[self.left_table].aggregate(pipeline)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\collection.py", line 1918, in aggregate
    collation=collation)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\collection.py", line 232, in _command
    collation=collation)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\pool.py", line 477, in command
    collation=collation)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Invalid $project specification: specification must have at least one field
[20/Dec/2017 08:32:51] "GET /workflow/ HTTP/1.1" 500 215076
[20/Dec/2017 08:32:51] "GET /static/debug_toolbar/img/ajax-loader.gif HTTP/1.1" 200 404
[20/Dec/2017 08:32:51] "GET /static/debug_toolbar/js/jquery_post.js HTTP/1.1" 200 118
[20/Dec/2017 08:32:51] "GET /static/debug_toolbar/js/jquery_pre.js HTTP/1.1" 200 136
[20/Dec/2017 08:32:51] "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 20322
[20/Dec/2017 08:32:51] "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 12552
[20/Dec/2017 08:32:51] "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 29
2017-12-20 08:32:53 WARNING django.request ##: Not Found: /favicon.ico
[20/Dec/2017 08:32:53] "GET /favicon.ico HTTP/1.1" 404 11861

**Comment by nesdis** [comment]
You srw

**Comment by nesdis** [comment]
You are totally right. I have added the print in the right place. Please try again. Thank you

**Comment by ayakut** [comment]
Hi @nesdis ,

Will check!

**Comment by ayakut** [comment]
Hi @nesdis ,

Your additional logging dosn't work because the pymongo processes exception before:
>C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\pool.py in command
        try:
            return command(self.sock, dbname, spec, slave_ok,
                           self.is_mongos, read_preference, codec_options,
                           check, allowable_errors, self.address,
                           check_keys, self.listeners, self.max_bson_size,
                           read_concern,
                           parse_write_concern_error=parse_write_concern_error,
                           collation=collation) ...
        except OperationFailure:
            raise
        # Catch socket.error, KeyboardInterrupt, etc. and close ourselves.
        except BaseException as error:
            self._raise_connection_failure(error)
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\network.py in command
        unpacked = helpers._unpack_response(
            response, codec_options=codec_options)
        response_doc = unpacked['data'][0]
        if check:
            helpers._check_command_response(
                response_doc, None, allowable_errors,
                parse_write_concern_error=parse_write_concern_error) ...
    except Exception as exc:
        if publish:
            duration = (datetime.datetime.now() - start) + encoding_duration
            if isinstance(exc, (NotMasterError, OperationFailure)):
                failure = exc.details
            else:
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\helpers.py in _check_command_response
                raise DuplicateKeyError(errmsg, code, response)
            elif code == 50:
                raise ExecutionTimeout(errmsg, code, response)
            elif code == 43:
                raise CursorNotFound(errmsg, code, response)
            msg = msg or "%s"
            raise OperationFailure(msg % errmsg, code, response) ...
def _check_gle_response(response):
    """Return getlasterror response as a dict, or raise OperationFailure."""
    response = _unpack_response(response)
▶ Local vars

I've debbuged and figured out, that it fall on the select:
>SELECT DISTINCT "viewflow_task"."flow_task" FROM "viewflow_task" INNER JOIN "viewflow_process" ON ("viewflow_task"."process_id" = "viewflow_process"."id") WHERE ("viewflow_process"."flow_class" IN (%(0)s, %(1)s, %(2)s) AND "viewflow_task"."owner_id" = %(3)s AND "viewflow_task"."status" = %(4)s) ORDER BY "viewflow_task"."flow_task" ASC LIMIT 21

response is:
>OperationFailure at /workflow/
Invalid $project specification: specification must have at least one field
Request Method:	GET
Request URL:	http://127.0.0.1:8000/workflow/
Django Version:	1.11.7
Exception Type:	OperationFailure
Exception Value:	
Invalid $project specification: specification must have at least one field
Exception Location:	C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\helpers.py in _check_command_response, line 210
Python Executable:	C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe
Python Version:	3.6.2
Python Path:	
['C:/Users/alexk/development/projects/python/fifa_mongo',
 'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',
 'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo',
 'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',
 'C:\\Users\\alexk\\.PyCharm2017.3\\system\\cythonExtensions',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\Scripts\\python36.zip',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\DLLs',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\lib',
 'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\setuptools-28.8.0-py3.6.egg',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\pip-9.0.1-py3.6.egg',
 'c:\\users\\alexk\\development\\projects\\python\\djongo',
 'C:\\Program Files\\JetBrains\\PyCharm '
 '2017.2.3\\helpers\\pycharm_matplotlib_backend',
 'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo']
Server time:	Wed, 20 Dec 2017 17:34:18 +0000
Traceback Switch to copy-and-paste view
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\handlers\exception.py in inner
            response = get_response(request) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\handlers\base.py in _get_response
                response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\core\handlers\base.py in _get_response
                response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\views\generic\base.py in view
            return self.dispatch(request, *args, **kwargs) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\viewflow\compat.py in _wrapper
            return bound_func(*args, **kwargs) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\contrib\auth\decorators.py in _wrapped_view
                return view_func(request, *args, **kwargs) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\viewflow\compat.py in bound_func
                return func.__get__(self, type(self))(*args2, **kwargs2) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\material\frontend\views\list.py in dispatch
        self.object_list = self.get_object_list() ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\material\frontend\views\list.py in get_object_list
            self.filterset = self.get_filterset(filterset_class) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django_filters\views.py in get_filterset
        return filterset_class(**kwargs) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\viewflow\frontend\filters.py in __init__
                 for task_ref in tasks] ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py in __iter__
        self._fetch_all() ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py in _fetch_all
            self._result_cache = list(self._iterable_class(self)) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\query.py in __iter__
        for row in compiler.results_iter(): ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py in results_iter
        for rows in results: ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py in cursor_iter
                         sentinel): ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\models\sql\compiler.py in <lambda>
        for rows in iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)), ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\django\db\utils.py in inner
                return func(*args, **kwargs) ...
▶ Local vars
c:\users\alexk\development\projects\python\djongo\djongo\cursor.py in fetchmany
                ret.append(self.result.next()) ...
▶ Local vars
c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in __next__
        return next(self._result_generator) ...
▶ Local vars
c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in __iter__
            raise e ...
▶ Local vars
c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in __iter__
            yield from iter(self._query) ...
▶ Local vars
c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in __iter__
                self._cursor = self._get_cursor() ...
▶ Local vars
c:\users\alexk\development\projects\python\djongo\djongo\sql2mongo.py in _get_cursor
            cur = self._result_ref.db[self.left_table].aggregate(pipeline) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\collection.py in aggregate
                                           collation=collation) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\collection.py in _command
            collation=collation) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\pool.py in command
                           collation=collation) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\network.py in command
                parse_write_concern_error=parse_write_concern_error) ...
▶ Local vars
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\pymongo\helpers.py in _check_command_response
            raise OperationFailure(msg % errmsg, code, response) ...
▶ Local vars

**Comment by nesdis** [comment]
Thanks for that I will check this SQL. 

This is the code which is added:

```python
        try:
            yield from iter(self._query)
        except SQLDecodeError as e:
            print(self._sql)
            e.err_sql = self._sql
            raise e
        except OperationFailure as e:
            print(self._sql)  #  << print SQL
            print(e.details)
            raise e
```

In the traceback you have shared I see this function is called, So in case of OperationFailure, the SQL should have been printed as get_cursor was called from iter, why was it not printed?

**Comment by ayakut** [comment]
Hi @nesdis ,

Sure, I saw this code. But the matter is the "except" parts don't work because of the pymongo catches all exceptions up and doesn't throw them further.

**Comment by nesdis** [comment]
@ayakut It took me some time to implement this issue. Djongo now does all nested lookups **without making two trips** to the database!!

The nested queries are now handled using the new aggregation `$lookup` syntax introduce in MongoDB 3.6. which means they are now **super efficient** 😀 I hope you get a chance to check if this solves the errors we are facing.

Thank you for your patience.

**Comment by ayakut** [comment]
Hi @nesdis,

Thank you for the update!
It is a good news! 
Sure, I'll check it out and will reply with a status of the checks!

**Comment by nesdis** [comment]
Hi @ayakut please open a new ticket in case you face any issues.
