### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.

### ISSUE THREAD

**Issue by woue1989** [nesdis/djongo#346]
#### Python script

<The complete python script used to produce the issue.>

```python

for django3.0
```

#### Traceback
<The complete stack trace of the error.>

**Comment by autumnwater935** [comment]
i think djongo do not support django 3.0 now.
Django           3.0
djongo           1.2.38
get error

> django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'

**Comment by 4rch18** [comment]
Mark duplicate. Source of this is same as the following issue:
> https://github.com/nesdis/djongo/issues/341

**Comment by FernandoBoza** [comment]
i'm getting the same when trying to hook up to mlabs but using Django 2.2.10

```
Django          2.2.10 
djongo          1.3.1
```
