### ISSUE TITLE
django.utils not an available backend issue solved.

### ISSUE THREAD

**Issue by aaman123** [nesdis/djongo#357]
This error occurs because the django utils.py file does not recognize that django is an available backend, 
to solve this error , please follow these steps...
1 . Go to C:\Users\User\AppData\Local\Programs\Python\Python38-32\Lib\site-packages and find 
      the djongo folder . 
2. Now cut and paste the djongo folder in the 
    C:\Users\aman\AppData\Local\Programs\Python\Python38-32\Lib\site - 
    packages\django\db\backends   directory . 
3. Now u might be getting the error cannot import six from django.utils. For resolving that go to 
    C:\Users\aman\AppData\Local\Programs\Python\Python38-32\Lib\site  - 
    packages\django\db\backends\djongo\operations.py file and replace the line from django.utils 
    import six , datetime to from django.utils import datetime and beneath that just write import six .
4. Now in the settings.py file of your django project add the lines 
   DATABASES = {
     'default': {
         'ENGINE': 'django.db.backends.djongo',
         'NAME': 'your-database-name',
     }
 }
5. That should resolve the problem ....

_Originally posted by @aaman123 in https://github.com/nesdis/djongo/issues/171#issuecomment-571087529_

**Comment by PrateekSai** [comment]
will this cause any future issues
