### ISSUE TITLE
DecimalField converts to String in mongo instead of Decimal128

### ISSUE THREAD

**Issue by lyapizz** [nesdis/djongo#378]
Hey devs,

#### One line description of the issue
DecimalField converts to String in mongoDB instead of Decimal128

I am newbie with djongo, but this behavior look strange for me.
#### Python script

1) I created test model with one DecimalField inside.
```python

from django.db import models
class TestDecimal(models.Model):
    average = models.DecimalField(max_digits=6, decimal_places=3, default=Decimal(0.0))

```

2) Then I create new TestDecimal object via admin
![insert_new_decimal](https://user-images.githubusercontent.com/5147073/77348814-280ae980-6d4b-11ea-9e08-733a0f40038f.JPG)

3) In mongoDB I see string value instead of Decimal128

![mongo_db_record](https://user-images.githubusercontent.com/5147073/77349024-71f3cf80-6d4b-11ea-80cf-4f38d2c339b7.JPG)

4) After loading back TestDecimal.average stays str object.

a) Should I made some special settings to fix that?
or
b) Should I cast every get from db?

#### Traceback
This problems leads to TypeError exception while manipulating with Decimal

Regards,
Pavel.

**Comment by antonio-irarrazaval** [comment]
Hi,
 In https://docs.djangoproject.com/en/3.0/ref/models/fields/#decimalfield , say:


> The default form widget for this field is a NumberInput when localize is False or TextInput otherwise.

You should try:
`revenue = forms.DecimalField(max_digits=4, decimal_places=2, localize=False)`

but you will have the . (dot) or , (comma) problem.
