### ISSUE TITLE
Document how to use Djongo with an existing MongoDB database

### ISSUE THREAD

**Issue by techdragon** [nesdis/djongo#38]
The documentation already explains how to use djongo so that djongo creates new collections for the django models. However it doesn't have any documentation on how to use djongo with an existing MongoDB collection that already contains documents.

~~Is this possible?~~ [Confirmed as possible](https://github.com/nesdis/djongo/issues/38#issuecomment-354736801)

~~If so,~~ It needs to be documented, ~~if not it would be an extremely useful feature~~.

**Comment by nesdis** [comment]
For an already existing database. Integrating into Django means you need to create __schema__ collection manually. Running manage.py makemigrations does this for you.

If models with data already exists in mongodb . Running manage.py makemigrations should not interfere with existing data and should automatically get integrated

**Comment by techdragon** [comment]
@nesdis Thanks for the quick answer. I've edited the issue title to be a more relevant and actionable item for a later pull request.

**Comment by christianbueno1** [comment]
hello pals , please help me with this [question](https://stackoverflow.com/questions/48245791/how-read-collections-of-mongodb-on-django-environment).
An for another example , whats if my collections is this tiny [file](https://drive.google.com/open?id=1NK_gdCcNGpzo4-B4sardBw8kBZ8UNaoA)

**Comment by nesdis** [comment]
@christianbueno1. Your assumption in the question is right and that is the correct way of doing it!

Regarding using an existing db for your work i would suggest the following procedure:

1. Start with an empty db
2. Define your models in Django exactly the same as the fields in existing db.
3. run manage.py makemigarations followed by manage.py migrate. At the end of this step your empty db should have a `__schema__` collection as well as other collections defined in your model.py
4. Copy all data from existing db to new db
5. In `__schema__` collection make sure the `auto` field with `field_name` : `id`, `seq` number is incremented to the latest value corresponding to the copied data set. (`seq` will be 0 for all copied collections)

**Comment by nesdis** [comment]
A section on migrating to djongo with an existing DB has been added to the [main tutorial](https://nesdis.github.io/djongo/integrating-django-with-mongodb/)

**Comment by subodhk01** [comment]
i had a django app working completely fine with mongodb but now a created a new app with exactly same models and same mongo database. When I applied makemigrations it was successfull but when I try to apply migrate, it shows that collection already exists, should i worry coz the app is still in complete but the django admin works fine.

**Comment by nelson26-shruti-mom** [comment]
I try lot of times to migrate my files from Django to MongodB.  Installed_Apps files are not migrated to my MongodB database.
What is the problem behind that....???

I am creating the API which is having CRUDE (CREATE, UPDATE, DELETE) Operation. For that purpose i am creating superuser , but it doesn't shows My CUSTOMER app after login in the browser.
