### ISSUE TITLE
Database connection 

### ISSUE THREAD

**Issue by antonio-irarrazaval** [nesdis/djongo#381]
Database connection fails as description setup in documentation. May this is not a bug or issue, may by only update the documentation

```python
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': False,
        'NAME': 'ticket_v3',
        'CLIENT': {
            'HOST': '192.168.0.26',
            'PORT': 27017,
            'USER': 'super_user',
            'PASSWORD': 'super_passord',
            'AUTH_SOURCE': 'admin',
            'AUTH_MECHANISM': 'SCRAM-SHA-1',
        },
        'LOGGING': {
            'version': 1,
            'loggers': {
                'djongo': {
                    'level': 'DEBUG',
                    'propogate': False,
                }
            },
        },
    }
}

```

BUT, making a little change, removing the CLIENT dict, and moving up the items.

```python
DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': False,
        'NAME': 'ticket_v3',
        'HOST': '192.168.0.26',
        'PORT': 27017,
        'USER': 'ant1',
        'PASSWORD': '123456',
        'AUTH_SOURCE': 'admin',
        'AUTH_MECHANISM': 'SCRAM-SHA-1',
        'LOGGING': {
            'version': 1,
            'loggers': {
                'djongo': {
                    'level': 'DEBUG',
                    'propogate': False,
                }
            },
        },
    }
}
```

works fine as expected.

 long life to djongo!

**Comment by Naumansh** [comment]
@antonio-irarrazaval  
glad you gotta fix. i am using below settings but seeing pymongo.errors.OperationFailure: command listCollections requires authentication

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'ENFORCE_SCHEMA': False,
        'NAME': 'admin',
        'HOST': '127.0.0.1',
        'PORT': 27017,
        'USER': 'xxx',
        'PASSWORD': 'xx1',
        'AUTH_SOURCE': 'admin',
        'AUTH_MECHANISM': 'SCRAM-SHA-1'
    }
}

Any idea?

**Comment by ernestoarbitrio** [comment]
same error here `pymongo.errors.OperationFailure: command listCollections requires authentication`

**Comment by ernestoarbitrio** [comment]
ok a downgrade to 1.2.30 fixed my issue
