### ISSUE TITLE
Adding field to existing model, but it didn't work

### ISSUE THREAD

**Issue by RHxW** [nesdis/djongo#411]
#### when I add a new field to an existing model,it didn't add the new field to old data
Hi, I have a model `Dataset`,it has several fields and I already have some data in it.
And I want to add a BooleanField called `is_active` to `Dataset`,I do `python manage.py makemigrations` and `python manage.py migrate`,they both work fine.
But when I check the database,the old data rows didn't have the `is_active` field, and when I try to get the old data with Django ORM objects (like using `Dataset.objects.all()`), error happens.
error like:
```djongo.sql2mongo.MigrationError: is_active```
And I can add a new data using Django ORM,the new data has the field of `is_active`.
If I get the new data by id,it works just fine.
But when I try to get the old data by id,the same error happens.
So I think the problem is,when I add a field to a model,djongo doesn't add it to the existing/old data,just the new ones.
This is really important.How can I fix it?

this is my env packages:
```
Package             Version
------------------- -------
bson                0.5.8
dataclasses         0.6
Django              2.2.12
django-cors-headers 3.2.1
djangorestframework 3.11.0
djongo              1.2.31
Pillow              7.1.2
pip                 20.1
pymongo             3.10.1
python-dateutil     2.8.1
pytz                2020.1
setuptools          46.1.3
six                 1.14.0
sqlparse            0.2.4
wheel               0.34.2
```
#### Python script

<The complete python script used to produce the issue.>

```python
<copy and paste code here>

```

#### Traceback
<The complete stack trace of the error.>

**Comment by SebastianRemander** [comment]
[Documentation](https://nesdis.github.io/djongo/get-started/) covers the behavior you described:

> When connecting to Djongo you can set ENFORCE_SCHEMA: True. In this case, a MigrationError will be raised when field values are missing from the retrieved documents. You can then check what went wrong.

and (what might be a possible solution for your issue)

> ENFORCE_SCHEMA: False works by silently setting the missing fields with the value None. If your app is programmed to expect this (which means it is not a bug) you can get away by not calling any migrations.

I assume that you can also fix the issue by connecting to your mongoDB using `mongod`, and updating the old data to have the `is_active` field set to a value you like, for each old document.

NOTE: I described how you can fix this issue and get your app working again, but it does not remove the real issue i.e. running migrations seems to work unexpectedly. However, `ENFORCE_SCHEMA: False` per documentation seems to be there exactly for avoiding running migrations on a non-empty database - I don't have the expertise to help with the migrations..

**Comment by RHxW** [comment]
Yes, thank you very much, you are right
I set `ENFORCE_SCHEMA` to `False` and there are no error again.
But still, the djongo ORM won't update the old data, I guess maybe it's just too hard to update the existing data in a nosql database.
Again, thanks a lot
