### ISSUE TITLE
pip install djongo reverts django 3.0.3 to 2.2.12

### ISSUE THREAD

**Issue by rgvillanueva28** [nesdis/djongo#420]
I have installed django 3.0.3 using pip but when I add djongo using pip also, it uninstalls django 3.0.3 and installs django 2.2.12

Will it work if I install django 3.0.3 again?

**Comment by devbihari** [comment]
I doubt. As far as I know Djongo is currently not compatible with Django 3.0.3

**Comment by bsdis** [comment]
any plans to upgrade djongo to work w. django 3.x?

**Comment by SebastianRemander** [comment]
> any plans to upgrade djongo to work w. django 3.x?

Looking at the latest [commit](https://github.com/nesdis/djongo/commit/b67cea23b841d68e1832c42d19b45d995ac4a796) (well, only the message :see_no_evil: ) and active branches, it seems so.

**Comment by rgvillanueva28** [comment]
I saw from the requirements.txt of the repo that Django 3.0 is supported. 3.0.3 isn't though.

**Comment by stefanbschneider** [comment]
This is still an issue with the latest `djongo 1.3.2` release on PyPi. It's incompatible with Django 3.
