### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tbobm** [nesdis/djongo#46]
In order to ease a bit contributions, I'd like to make the codebase (which is getting a bit dense), a bit more documented, but I can't do it alone, because there are some parts of the code I don't understand.

Would you mind putting this on the "roadmap"?

As I told you I'd like to contribute to djongo, but there is a lot to discover, and a more verbose code, or a more documented one would greately increase the overwhole attractiveness of extern contributions I think.

Thanks in advance @nesdis ! 😁

**Comment by nesdis** [comment]
I agree the code is missing documentation in terms of comments and docstrings. More focus has been to document its application. At some point I will add docstrings to the various classes. (If you understand a class or part of code, please go ahead and add a docstring to it. I will add more or just merge it.) On the other hand, my **personal** opinion is that the class names, function names are self explanatory. 

The roadmap at the moment consists of solving issues reported by other users. The Django ORM is used by other apps like viewflow or rest framework. As users use it with this other apps, issues can crop up. I still have not solved some of them. #33 

The good news is 'LIKE' operator is now added! You can create a clone and check if it works for you.

I encourage you to create or add to the markdowns inside the 'docs' folder on topics which you want covered. I can try and document the topics which you want.

**Comment by rudolfce** [comment]
I've been having a hard time with my personal projects lately, but I might be able to help with some module docstrings, if it helps.

**Comment by nesdis** [comment]
Yes, please go ahead

**Comment by nesdis** [comment]
@rudolfce If you decide to taken on the task of writing doc strings for the module and classes shall I assign this issue to you?

**Comment by rudolfce** [comment]
It wouldn't make for a full documentation task, but if you guys think docstrings would be enough to close the issue, then yes, no problem.

**Comment by WoLpH** [comment]
While the current docs site is quite nice, it might be a good addition to add some auto generated API docs using Sphinx. They can be automatically hosted on ReadTheDocs without too much effort. Shouldn't be more than an hour of work to get it all up and running
