### ISSUE TITLE
Access to MongoDB `_id` value without requiring it to be referenced in Model.

### ISSUE THREAD

**Issue by techdragon** [nesdis/djongo#47]
#### Providing access to the MongoDB ObjectID object of any Djongo Model object instance will improve usefulness.

Bypassing limitations in Djongo will typically involve making direct queries to MongoDB. While there is an existing mechanism for this, it lacks the ability to base such queries on data from an existing object. I cannot use Djongo to query an object, then use a decorator/property to perform a specific MongoDB query based on the object I'm currently working with. For example,  simple model query with Djongo, perform complex map reduce with raw `pymongo` via `object.*` where the map reduce requires the ObjectID of the result of the simple query. An alternative example, I want to add a property to my model `Foo` which is the count of all `Bar` models which have an `ObjectID` reference to `Foo` matching a complex criteria expressed with raw `pymongo`.

Requiring the addition of `_id = models.IntegerField(db_column='_id')` wherever we want to have the same ease of use as "regular Django" gives us by using the `self.id` and `self.pk` directly. It can be cloaked behind some `_` property, like `self._mongodb_objectid` or just `self._id`, but either way the usefulness of Djongo would be increased by not having to put `_id = models.IntegerField(db_column='_id')` manually on models.

**Comment by nesdis** [comment]
Hi @techdragon I plan to move your enhancement suggestions to the main documentation on the __roadmap__ page for better visibility and viewership.

Thank you for your contributions!
