### ISSUE TITLE
Use _id instead of id

### ISSUE THREAD

**Issue by brunowego** [nesdis/djongo#488]
#### One line description of the issue

Hi everybody! I'm new using Djongo. Have a way to use `_id` by default instead of `id`?

<img width="578" alt="Screen Shot 2020-10-29 at 8 16 27 AM" src="https://user-images.githubusercontent.com/441774/97561659-44e15c80-19bf-11eb-9d04-2a28f98e107d.png">

```txt
Django==2.2.16
sqlparse==0.2.4
djongo==1.3.3
djangorestframework==3.12.1
```

**Comment by stefanodecillis** [comment]
How did you solve it?

**Comment by brunowego** [comment]
@stefanodecillis I not remember, but I think it is not possible because MongoDB.

**Comment by brunowego** [comment]
Instead, I change in `serializers.py`

```py
class CampaignSerializer(DjongoModelSerializer):
    campaign = serializers.CharField(source='_id', read_only=True)
```

**Comment by stefanodecillis** [comment]
Oh okay, I see. Actually, it's about two days that I'm using Djongo but I will move to PyMongo.
The documentation is missing (the one online is not well explained and it covers only the basic of the base case) and it seems like there is not so much you can control, at least on the few questions I found over here. I will rather write the queries by myself and lose the model support.
