### ISSUE TITLE
AWS documentDB connection error(SSL fail)

### ISSUE THREAD

**Issue by bhkim1020** [nesdis/djongo#545]
#### One line description of the issue
Hello, I have problem about AWS documentDB connection error(in makeintegration).....
and I do not solve it.
Please help me about this problem.

#### Python script

<The complete python script used to produce the issue.>

settings.py

```{.python}

DATABASES = {
    'default': {
        'ENGINE': 'djongo', # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'xxx',                      # Or path to database file if using sqlite3.
        'CLIENT': {
            'host': os.getenv('MONGODB_HOST', 'docdb-zzzzz.cluster-qqqq.eu-west-x.docdb.amazonaws.com'),
            'port': int(os.getenv('MONGODB_PORT', 27017)),
            'username': os.getenv('MONGODB_USERNAME', 'aaaa'),
            'password': os.getenv('MONGODB_PASSWORD', 'yyyy'),
            'authMechanism': os.getenv('MONGODB_AUTHMECHANISM', 'SCRAM-SHA-1'), 
            'ssl': os.getenv('MONGODB_SSL', True),
            'ssl_ca_certs': '/app/rds-combined-ca-bundle.pem',
            #'ssl_cert_reqs' : os.getenv('MONGODB_SSL_CERT_REQUIRED', 'ssl.CERT_NONE'),
            #'tlsAllowInvalidCertificates': os.getenv('MONGODB_TLSALLOWINVALIDCERTIFICATES', True),
            #'retryWrites': os.getenv('MONGODB_RETRYWRITES', False),
            'readPreference': "secondaryPreferred",
            'replicaSet':'rs0'
        },
        'PORT': '27017',                      # Set to empty string for default.
    }
}
```

#### Traceback
<The complete stack trace of the error.>

pymongo.errors.ServerSelectionTimeoutError: docdb-zzzzz.cluster-qqqq.eu-west-x.docdb.amazonaws.com:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091), Timeout: 30s, Topology Description: <TopologyDescription id: 60a5c975cd0dc6f766470e21, topology_type: Single, servers: [<ServerDescription ('docdb-zzzzz.cluster-qqqq.eu-west-x.docdb.amazonaws.com', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('docdb-zzzzz.cluster-qqqq.eu-west-x.docdb.amazonaws.com:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')>]>

How can I change settings.py for using AWS documentDB?
Best Regards!

**Comment by jttttttttttttt** [comment]
Hi, how can I set in django:
'mongo': {
        'ENGINE': "djongo",
        'NAME': DATABASES_NAME,
        'CLIENT': {
            'host': "mongodb://<user>:<pass>@<host>:27017",
        }
    }
Can you slove the problem?
