### ISSUE TITLE
Help: Django 3.2.4 does not detect ObjectIdField as AutoField

### ISSUE THREAD

**Issue by Feelixe-tin** [nesdis/djongo#555]
I'm running Django 3.2.4.
In my app I've configured an AutoField like this:
```
class MyAppConfig(AppConfig):
    name = 'myapp'
    default_auto_field = 'djongo.models.fields.ObjectIdField'
```

When running `makemigrations` I get this error:
```
ValueError: Primary key 'djongo.models.fields.ObjectIdField' referred by myapp.apps.MyAppConfig.default_auto_field must subclass AutoField.
```

It seems like Django is not detecting `ObjectIdField` as an AutoField.

If I set `default_auto_field` to just AutoField it will work but then in my MongoDB database, I'll have two id fields, one `_id` with mongo object id and one `id` incremented integer.

Does anyone know a solution?

**Comment by underscoreanuj** [comment]
@Feelixe-tin I was facing a similar problem, the documentation mentions using the _id field explicitly in your model. It resolved the issue in my case: 
[refer](https://www.djongomapper.com/using-django-with-other-fields/#the-objectid-field)
hope this helps.
