### ISSUE TITLE
A problem with __schema__ and ForeignKey

### ISSUE THREAD

**Issue by mukundshah** [nesdis/djongo#557]
### Hi everyone!

I'm working on a Django project with MongoDB. And I spent almost 14 hours (30 hours if I count the last attempt 😁😁) in a row to solve an issue with my project. So it's like this:

I shifted my old Django project from SQLite to djongo, and it broke. Spent 10-12 hours trying to fix it. Eventually, I got frustrated and started from scratch, and it worked, and again broke.
The issue is that the `__schema__` kicks in when there is only one app and one model. As soon as multiple models in one app or one model across many apps or many models along many apps is used, `__schema__` doesn't do its job: storing record for auto-incrementing. Things become more ugly when ForeignKey is introduced

A workaround for this was to set `_id` as `primary_key`. Well, that works, but ForeignKey is still messed up.

Another solution, which I found in the issues of this repo after deep-digging, – which I suppose programming is all about: digging the old graves😂😂 – was to use UUID.

```
import uuid

class Whatever(models.Model):
      id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

It perfectly worked, and solved the issue of ForeignKey, but didn't feel elegant to me. I wanted that serial numeric id.

After a five-minute break, an idea hit me: manually add an entry for my model in the `__schema__`, and guess what, it worked.

```
#my entry
{
    "name": "course_course",
    "auto": {
        "field_names": ["id"],
        "seq": 4
    },
    "fields": {
        "id": {
            "type_code": "long"
        },
        "university_id": {
            "type_code": "Binary"
        },
        "subject_id": {
            "type_code": "Binary"
        },
        "course_title": {
            "type_code": "string"
        },
        "course_code": {
            "type_code": "string"
        },
        "syllabus": {
            "type_code": "string"
        }
    }
}
```
This how exactly I added in the `__schema__`. It was a tedious job to add this entry😁😁

I finally got what I needed. However, this isn't a viable way to mitigate this, is this?
So, it's my request that if you can look into this? Also was this only my issue and there is another fix, or is this a real issue with djongo? Let me know.

**Looking forward to your responses.**

**Comment by mukundshah** [comment]
@rudolfce

**Comment by rudolfce** [comment]
Hello, @mukundshah. I think I managed to reproduce the errors and fixes you listed.

If your error was the same as mine, you need to make migrations for your apps and migrate them. This will generate the `__schema__` entries and indexes.

After a migration I was able to use the sequential integer id and foreign keys. Could you please let me know if this solves your problem?

Regards

**Comment by mukundshah** [comment]
Hi there, @rudolfce.
I used `makemigrations` and `migrate`, but it didn't do anything. I also tried with new db, same as always. 
And I'm using `django.db.model`. I will try again with `djongo.model`.
