### ISSUE TITLE
Unknown database engine djongo

### ISSUE THREAD

**Issue by ayakut** [nesdis/djongo#56]
Hi @nesdis ,

When I try to reset my DB, I got next error:
```
(fifa_mongo) C:\Users\alexk\development\projects\python\fifa_mongo>manage.py reset_db --settings=settings_dev

You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "fifa_mongo".
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
CommandError: Unknown database engine djongo
```

**Comment by nesdis** [comment]
reset_db is command not native to Django. and Django-extensions unfortunately does not recognize Djongo as a db engine.

**Comment by g-curtis-edacious** [comment]
For anyone else that lands here:

https://django-extensions.readthedocs.io/en/latest/reset_db.html#optional-settings
