### ISSUE TITLE
Strange inserting in Admin

### ISSUE THREAD

**Issue by ayakut** [nesdis/djongo#57]
Hi @nesdis ,
There was found strange behavior of the Django-Admin + djongo.
When I'm trying to edit some entity:
![image](https://user-images.githubusercontent.com/2535670/35349258-1abd3592-0143-11e8-9907-7af20f0aa06a.png)

And without any changes want to Save the entity:
![image](https://user-images.githubusercontent.com/2535670/35349358-5e455a42-0143-11e8-8b99-82ac4ee46d1f.png)

Then I got an error:
```

Request Method: | POST
-- | --
http://127.0.0.1:8000/admin/flows/provider/35/change/
1.11.7
SQLDecodeError
FAILED SQL: INSERT INTO "flows_provider" ("id", "name", "ptype", "homepage_url", "deeplink_template", "discovery_plugin_config") VALUES (%(0)s, %(1)s, %(2)s, %(3)s, %(4)s, %(5)s)Pymongo error: {'index': 0, 'code': 11000, 'errmsg': 'E11000 duplicate key error collection: fifa_mongo.flows_provider index: __primary_key__ dup key: { : 35 }'}
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\lib\site-packages\djongo\sql2mongo.py in parse, line 886
C:\Users\alexk\development\projects\python\venvs\fifa_mongo\Scripts\python.exe
3.6.2
['C:/Users/alexk/development/projects/python/fifa_mongo',  'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',  'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo',  'C:\\Program Files\\JetBrains\\PyCharm 2017.2.3\\helpers\\pydev',  'C:\\Users\\alexk\\.PyCharm2017.3\\system\\cythonExtensions',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\Scripts\\python36.zip',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\DLLs',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36\\lib',  'C:\\Users\\alexk\\AppData\\Local\\Programs\\Python\\Python36',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\pip-9.0.1-py3.6.egg',  'C:\\Program Files\\JetBrains\\PyCharm '  '2017.2.3\\helpers\\pycharm_matplotlib_backend',  'C:\\Users\\alexk\\development\\projects\\python\\venvs\\fifa_mongo\\lib\\site-packages\\IPython\\extensions',  'C:\\Users\\alexk\\development\\projects\\python\\fifa_mongo']
Wed, 24 Jan 2018 18:16:16 +0000
```

the system tries to insert (not update!) the entity

and what interesting,  the seq id of the collection "flows_provider" increased in the any way (was before 38):
![image](https://user-images.githubusercontent.com/2535670/35349579-02317582-0144-11e8-8a0e-2b32ce0bc4c8.png)

>/* 21 createdAt:24/01/2018, 19:40:48*/
{
	"_id" : ObjectId("5a68c520480952409a5db717"),
	"name" : "flows_provider",
	"auto" : {
		"seq" : 39,
		"field_names" : [
			"id"
		]
	}
},

Here is stored data:
>/* 8 createdAt:24/01/2018, 20:01:11*/
{
	"_id" : ObjectId("5a68c9e76d933e026c7be862"),
	"id" : 35,
	"name" : "Expedia",
	"ptype" : "ota",
	"homepage_url" : "",
	"deeplink_template" : "",
	"discovery_plugin_config" : ""
}

What is strange:
On the screenshot we see values "Test " for some fields, but they there are not persist in the stored data!

**Comment by nesdis** [comment]
Yes there is some issue with the insertions. let me get back

**Comment by nesdis** [comment]
HI @ayakut this is now fixed
