### ISSUE TITLE
Cannot use MongoClient after close

### ISSUE THREAD

**Issue by kendimce** [nesdis/djongo#586]
Django Admin has started  throwing error randomly as "Cannot use MongoClient after close". The debug shows that it's Pymongo issue and i believe it's due to latest commit that was made 4 days ago as it started happening couple of days ago.

https://github.com/mongodb/mongo-python-driver/commits/master/pymongo/topology.py

Sometimes it works and fetches the data from Mongodb so it's not connection issue between Mongodb and Django.

![2021-12-13_17-31](https://user-images.githubusercontent.com/34376601/145831098-ef975638-9371-4ae2-85a1-7f59fff18e53.png)

**Comment by kendimce** [comment]
For the people who will have the same issue,
https://stackoverflow.com/questions/70185942/why-i-am-getting-not-implemented-error-database-objects-do-not-implement-truth

**Comment by mosi-kha** [comment]
fixed in my fork: https://github.com/mosi-kha/djongo
