### ISSUE TITLE
Problem with filtering embedded model fields

### ISSUE THREAD

**Issue by anthonyModeste** [nesdis/djongo#66]
Hello, 
I have this problem with filtering EmbeddedModel fields

Here is my model.py: 
#### model.py

<The complete python script used to produce the issue.>

```python
from djongo import models
from djongo.models import forms


class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    class Meta:
        abstract = True

    def __str__(self):
        return (self.name + ' - ' + self.tagline)


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = (
            'name', 'tagline',
        )


class Entry(models.Model):
    blog = models.EmbeddedModelField(
        model_container=Blog,
        model_form_class=BlogForm
    )

    headline = models.CharField(max_length=255)
    # objects = models.DjongoManager()

    def __str__(self):
        return(self.headline+' - '+ str(self.blog))


```
And here is my views.py: 
#### views.py

<The complete python script used to produce the issue.>

```python
from django.http import HttpResponse
from .models import Entry

def detail(request):

    entries = Entry.objects.filter(blog={'name': 'test'})
    print(entries)
    return HttpResponse("Your entries" + str(entries))



```
The problem is the code above doesn't work. Filter returns no entries and I've no ideas why.
Here are packages I use:
```python
pip3.6 freeze
dataclasses==0.4
Django==2.0.2
djongo==1.2.20
pymongo==3.6.0
pytz==2018.3
sqlparse==0.2.4
```
Thank You for the support.
Best

**Comment by nesdis** [comment]
There is an issue with querying embedded models. Some parts of it are still WIP. I will notify you as soon as they are checked into git.

**Comment by ferlnand** [comment]
@anthonyModeste Hi, problem is when filtering, EmbeddedModelFields seem to be compared to db-entries as a whole field and you can't filter by just one field out of it. Just out of curiosity try 
```python
entries = Entry.objects.filter(blog={'name': 'test', 'tagline': '<insert tagline of the Blog>'})
```

I know, this isn't a solution, but maybe(?) an explanation

**Comment by anthonyModeste** [comment]
@ferlnand Hi, the filter you mentioned works. But it means that the filter is not filtering the fields inside EmbeddedModelField. They need to be exactly the same to hit the query. For example when you just swap the position of 'name' and 'tagline':
```python
entries = Entry.objects.filter(blog={'tagline': '<insert tagline of the Blog>'},'name': 'test')
```
it does'nt work. This is obviously not the way it was designed to work. I'm just gonna wait for fix.
Best

**Comment by sshishov** [comment]
Hi @nesdis, we are also waiting for the fix. Good product but without this functionality embedded models are useless...
