### ISSUE TITLE
KeyError when we do not have the key in MongoDB

### ISSUE THREAD

**Issue by ravinarayansingh** [nesdis/djongo#67]
#### model.py

```
class Example(models.Model):
    name = models.CharField(max_length=30)
    age = models.IntegerField()
    salary = models.IntegerField()

result =  Example.objects.filter(age__gte=26).values('salary')
```
Actually in MongoDB, if we don't have a key in the collection then it will return null. 

#### Traceback
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\djongo\sql2mongo\query.py", line 259, in _align_results
    ret.append(doc[selected.column])
KeyError: 'salary'

**Comment by nesdis** [comment]
can you try once with the latest version?

**Comment by ravinarayansingh** [comment]
@nesdisI have tried in latest version only 

I have  added the below line in the align_result function in query.py of sql2mongo module 
```
if selected.column not in :
    continue
```
```
def _align_results(self, doc):
        ret = []
        if self.distinct:
            sql_tokens = self.distinct.sql_tokens
        else:
            sql_tokens = self.selected_columns.sql_tokens

        for selected in sql_tokens:
            if selected.table == self.left_table:
                try:
                    if selected.column not in doc:
                        continue
                    ret.append(doc[selected.column])
                except KeyError:
                    raise MigrationError(selected.column)
            else:
                try:
                    ret.append(doc[selected.table][selected.column])
                except KeyError:
                    raise MigrationError(selected.column)

        return tuple(ret)```

what is your opinion?

**Comment by sandguardian** [comment]
@nesdis There is an issue with values obtained Django ORM.

`MyModel.objects.filter(author=request.user).values('id')` returns auto-increment primary key.

If I add another nested field query like below, it returns id that mongo generated automatically.
`MyModel.objects.filter(author=request.user).values('id', 'cost__name')`

**Comment by nesdis** [comment]
@ravinarayansingh Some improvements have been made to enforce schema enable disable handling. Your issue should be solved...
