### ISSUE TITLE
Can't use djongo

### ISSUE THREAD

**Issue by h0r1zon** [nesdis/djongo#7]
django.core.exceptions.ImproperlyConfigured: 'djongo' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
Error was: No module named 'django.db.backends.base

I don't know what to do
I did do pip install djongo

**Comment by nesdis** [comment]
Please follow the steps outlined in the Readme First documentation
