### ISSUE TITLE
Speed of django with nesdis/django

### ISSUE THREAD

**Issue by noyessie** [nesdis/djongo#72]
#### One line description of the issue

I have a preoccupation. when you convert sql request in mongoDB request. What happend to response times ???

what is the know weakness of nesdis/django ?

It is scalable ?

**Comment by nesdis** [comment]
Hello @noyessie That is an excellent question, would you be kind enough to raise this on the discussion group? 

That's because issue tend to close and users open news issues.

**Comment by noyessie** [comment]
Yes, but where is the discussion group ?

**Comment by nesdis** [comment]
https://nesdis.github.io/djongo/discuss/

**Comment by noyessie** [comment]
thank's. is done.

**Comment by rogeryen** [comment]
Sorry how do I get access to the discussion group? It says `You do not have permission to access this content. (#418)`. Thanks in advance.
