### ISSUE TITLE
Updating Previous Records

### ISSUE THREAD

**Issue by valeriozhang** [nesdis/djongo#79]
Because Djongo creates automatic ID and AutoField(primary_key=True) fields, how can we update these fields since we all _id are stored as ObjectId() and not integers. Is there a way to get this? I am trying to update existing records, but the issue is I don't have access to the _id field since its an ObjectId with isn't decimal. How can I access the _id field?

https://docs.djangoproject.com/en/2.0/ref/models/instances/#explicitly-specifying-auto-primary-key-values

**Comment by nesdis** [comment]
You can access _id field like this:

class ReferenceBlog(models.Model):
   _id = models.ObjectIdField()

This will give you access to the internally created _id field
