### ISSUE TITLE
SQLDecodeError Count with Group By

### ISSUE THREAD

**Issue by christopher-wiko** [nesdis/djongo#89]
Hi,

I try to use the GroupBy aggregation to count my entries, but I get the following error. Could you please help me ?

How can I use annotate() to Group By my entries ? Thanks in advance

#### Python script

```python
count_entries = Package.objects.values('software').annotate(Count('software'))
```

#### Traceback
SQLDecodeError
FAILED SQL: SELECT "packages"."software_id", COUNT("packages"."software_id") AS "software__count" FROM "packages" GROUP BY "packages"."software_id" LIMIT 21 
Version: 1.2.23

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/djongo/sql2mongo/query.py in parse, line 518

/Library/Frameworks/Python.framework/Versions/3.6/bin/python3 3.6.4
['/Users/username/bin/web',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload',  '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages']

**Comment by E-ENGINEERING** [comment]
I guess that the error is produced by the **parse()** function of the class **SelectQuery**:

In fact the **sqlparse** library (https://github.com/andialbrecht/sqlparse) split the **GROUP BY** keyword in two keywords which is **GROUP** and by **BY**

So **SQLDecodeError** exception is raised (because never match _ORDER BY_ string)! 

I try to modified the function (please check bellow), but unfortunnalty I raised a new Exception in Django Framework side:
- **django/db/models/sql/compiler.py** in **apply_converters**, line **1007**
- **IndexError**: list index out of range

Please do you have any suggestion?

The modified parse function:
```python
class SelectQuery(Query):

    def parse(self):
        tok_id = 0
        st = self.statement
        tok = self.statement[0]
        kw = tokens.Keyword
        dml = tokens.DML

        while tok_id is not None:
            if tok.match(tokens.DML, 'SELECT'):
                c = self.selected_columns = ColumnSelectConverter(self, tok_id)

            elif tok.match(tokens.Keyword, 'FROM'):
                c = FromConverter(self, tok_id)

            elif tok.match(tokens.Keyword, 'LIMIT'):
                c = self.limit = LimitConverter(self, tok_id)

            elif tok.match(tokens.Keyword, 'ORDER'):
                c = self.order = OrderConverter(self, tok_id)
            
            elif tok.match(tokens.Keyword, 'OFFSET'):
                c = self.offset = OffsetConverter(self, tok_id)

            elif tok.match(tokens.Keyword, 'INNER JOIN'):
                c = InnerJoinConverter(self, tok_id)
                self.joins.append(c)

            elif tok.match(tokens.Keyword, 'LEFT OUTER JOIN'):
                c = OuterJoinConverter(self, tok_id)
                self.joins.append(c)

            # elif tok.match(tokens.Keyword, 'GROUP BY'):
            #    c = self.groupby = GroupbyConverter(self, tok_id)
                
            elif tok.match(tokens.Keyword, 'GROUP'):
                tok_id, tok = self.statement.token_next(tok_id)
                c = self.groupby = GroupbyConverter(self, tok_id)

            elif isinstance(tok, Where):
                c = self.where = WhereConverter(self, tok_id)

            else:
                raise SQLDecodeError

            tok_id, tok = self.statement.token_next(c.end_id)
```

**Comment by nesdis** [comment]
There is now support for groupby and this should be fixed.
